<section class="content-header">
	<h1>Nuevo Contacto</h1>

	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-user"></i> Contacto</a></li>
		<li class="active">Nuevo Contacto</li>
	</ol>

</section>

<section class="content">

	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title">
				<strong>Datos Contacto</strong>
			</h3>
		</div>
		<form role="form" id="formIngresoContacto">

			<div class="box-body">

				<div class="form-group">
					<label for="nombreClienteInput">Nombre</label> <input type="text"
						class="form-control" id="nombreClienteInput"
						name="nombreClienteInput" placeholder="Amanda L&oacute;pez">
				</div>

				<div class="form-group">
					<label for="emailClienteInput">Email</label> <input type="email"
						class="form-control" id="emailClienteInput"
						name="emailClienteInput" placeholder="contacto@email.com">
				</div>

				<div class="form-group">
					<label for="telefonoClienteInput">Telefono</label> <input
						type="text" class="form-control" id="telefonoClienteInput"
						name="telefonoClienteInput" placeholder="022-111 111">
				</div>

				<div class="form-group">
					<label for="celularClienteInput">Celular</label> <input type="text"
						class="form-control" id="celularClienteInput"
						name="celularClienteInput" placeholder="+569-111-111-11">
				</div>

				<div class="row">

					<div class="col-md-6">
						<div class="col-xs-4">
							<label for="boleteoCheck" style="padding:5px;">Boleteo</label> <input  type="checkbox"
								id="boleteoCheck" class="minimal">
						</div>
						<div class="col-xs-4">
							<label for="cobroCheck"  style="padding:5px;">Cobro</label> <input type="checkbox"
								id="cobroCheck" class="minimal">
						</div>
					</div>
				</div>


			</div>

			<div class="box-body">


				<!-- Mensajes del registro Conceptos -->
				<div class="form-group hide" id="mensajeCorrectoRegistro">

					<div class="alert alert-success alert-dismissable">
						<button type="button" class="close"
							id="buttonMensajeCorrectoRegistro" aria-hidden="true">&times;</button>
						<h4>
							<i class="icon fa fa-check"></i> Ok !
						</h4>
						<p>Contacto registrado correctamente</p>
					</div>

				</div>

				<div class="form-group hide" id="mensajeProblemasRegistro">
					<div class="alert alert-danger alert-dismissable">
						<button type="button" class="close"
							id="buttonMensajeProblemasRegistro" aria-hidden="true">&times;</button>
						<h4>
							<i class="icon fa fa-check"></i> Ops !
						</h4>
						<p>Problemas a crear un nuevo contacto</p>
					</div>
				</div>

				<div class="form-group hide" id="mensajeEmailEncontrado">

					<div class="alert alert-warning alert-dismissable">
						<button type="button" class="close"
							id="buttonMensajeEmailEncontrado" aria-hidden="true">&times;</button>
						<h4>
							<i class="icon fa fa-check"></i> Opps !
						</h4>
						<p>El email que intenta registra ya se encuentra registrado</p>
					</div>

				</div>

			</div>


			<div class="box-footer">
				<button type="submit" class="btn btn-primary">
					Ingresar <span class="fa fa-save"></span>
				</button>
			</div>
		</form>
	</div>

</section>

<!-- Modal Alertas -->
<div class="modal modal-danger fade" id="modalAlertaErrorFormulario">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title">
					<strong>Alerta</strong>
				</h4>
			</div>
			<div class="modal-body">
				<p>Faltan Datos por completar</p>
			</div>
			<div class="modal-footer">
				<button type="button" data-dismiss="modal" class="btn btn-outline">
					<span class="glyphicon glyphicon-ok"></span>
				</button>
			</div>
		</div>
	</div>
</div>


<div class="modal modal-success fade" id="modalAlertaOkFormulario">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title">
					<strong>Ok</strong>
				</h4>
			</div>
			<div class="modal-body">
				<p>Datos registrados correctamente</p>
			</div>
			<div class="modal-footer">
				<button type="button" data-dismiss="modal" class="btn btn-outline">
					<span class="glyphicon glyphicon-ok"></span>
				</button>
			</div>
		</div>
	</div>
</div>
<!-- Termina Modal Alertas -->

