<section class="content-header">

	<h1>Mantenedor de Proveedores</h1>

	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-pencil"></i> Mantenedores</a></li>
		<li class="active">Mantenedor de Proveedores</li>
	</ol>

</section>

<section class="content">


	<div class="box box-primary">

		<div class="box-header with-border">
			<h3 class="box-title">
				<strong>Crean nuevo proveedor<strong>
			
			</h3>
		</div>
		<form role="form" action="" method="post" id="formNuevoProveedor">
			<div class="box-body">
				<div class="form-group">
					<label for="nombreProveedorInput">Clasificaci&oacute;n Proveedor</label>
					<input id="nombreProveedorInput" name="nombreProveedorInput"
						type="text" class="form-control" placeholder="Ingrese el Proveedor">
				</div>

				<!-- Mensajes del registro Proveedores -->

				<div class="form-group hide" id="mensajeCorrectoRegistro">

					<div class="alert alert-success alert-dismissable">
						<button type="button" class="close"
							id="buttonMensajeCorrectoRegistro" aria-hidden="true">&times;</button>
						<h4>
							<i class="icon fa fa-check"></i> Ok !
						</h4>
						<p>Proveedor creado correctamente</p>
					</div>

				</div>

				<div class="form-group hide" id="mensajeProblemasRegistro">

					<div class="alert alert-danger alert-dismissable">
						<button type="button" class="close"
							id="buttonMensajeProblemasRegistro" aria-hidden="true">&times;</button>
						<h4>
							<i class="icon fa fa-check"></i> Ops !
						</h4>
						<p>Problemas a crear un nuevo proveedor</p>
					</div>

				</div>

				<div class="form-group hide" id="mensajeRegistroNombreIgual">

					<div class="alert alert-warning alert-dismissable">
						<button type="button" class="close"
							id="buttonMensajeRegistroNombreIgual" aria-hidden="true">&times;</button>
						<h4>
							<i class="icon fa fa-check"></i> Ops !
						</h4>
						<p>El proveedor que trata de registrar ya existe</p>
					</div>

				</div>

			</div>


			<div class="box-footer">
				<button type="submit" class="btn btn-primary">
					Guardar <span class="fa fa-save"></span>
				</button>
			</div>
		</form>
	</div>

	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title">
				<strong>Listado de Proveedores<strong>
			
			</h3>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="box-body">

					<div class="form-group">
						<table id="tableMantenedorProveedores"
							class="table table-bordered table-hover cell-border compact">

							<thead>
								<th>Id</th>
								<th>Clasificaci&oacute;n del Proveedor</th>
							</thead>

						</table>
					</div>

					<div class="form-group hide" id="seleccionaConceptoLista">

						<div class="alert alert-warning alert-dismissable">
							<button type="button" class="close" id="buttonCierraMsgSeleccion"
								aria-hidden="true">&times;</button>
							<h4>
								<i class="icon fa fa-check"></i> Opps !
							</h4>
							<p>Primero debe seleccionar un proveedor</p>
						</div>

					</div>

					<div class="form-group hide" id="conceptoEliminado">

						<div class="alert alert-success alert-dismissable">
							<button type="button" class="close" id="buttonCierraMsgEliminado"
								aria-hidden="true">&times;</button>
							<h4>
								<i class="icon fa fa-check"></i> Ok !
							</h4>
							<p>Proveedor eliminado correctamente</p>
						</div>

					</div>

					<div class="form-group hide" id="conceptoActualizado">

						<div class="alert alert-success alert-dismissable">
							<button type="button" class="close"
								id="buttonCierraMsgActualizado" aria-hidden="true">&times;</button>
							<h4>
								<i class="icon fa fa-check"></i> Ok !
							</h4>
							<p>Proveedor actualizado correctamente</p>
						</div>

					</div>

					<div class="form-group hide" id="mensajeProblemaAccion">

						<div class="alert alert-danger alert-dismissable">
							<button type="button" class="close"
								id="buttonMensajeProblemaAccion" aria-hidden="true">&times;</button>
							<h4>
								<i class="icon fa fa-check"></i> Ops !
							</h4>
							<p>Problemas al realizar la acci&oacute;n</p>
						</div>

					</div>

				</div>

				<div class="box-footer">
					<div class="form-group">
						<button class="btn btn-success marginBottomButton editUser"
							id="buttonEditaProveedor">
							Modificar <span class="fa fa-edit"></span>
						</button>
						<button class="btn btn-danger marginBottomButton deletUser"
							id="buttonEliminarProveedor">
							Eliminar <span class="fa fa-remove"></span>
						</button>
					</div>
				</div>

			</div>

		</div>
	</div>

	<!---------- Ventanas Modales ---------->

	<!-- Modal Borrar Proveedor -->
	<div class="modal modal-danger fade" id="modalEliminarProveedor">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"
						aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<h4 class="modal-title">
						<strong>Eliminar Proveedor</strong>
					</h4>
				</div>
				<div class="modal-body">
					<p>Est&aacute; a punto de eliminar un proveedor, seguro quiere
						realizar esta acci&oacute;n?</p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-outline pull-left"
						data-dismiss="modal">
						<span class="fa fa-remove"></span>
					</button>
					<button type="button" id="buttonEliminaProveedorOk"
						data-dismiss="modal" class="btn btn-outline">
						<span class="fa fa-check"></span>
					</button>
				</div>
			</div>
		</div>
	</div>
	<!-- Termina Modal Borrar Proveedor -->

	<!-- Modal Editar Proveedor -->
	<div class="modal modal-success fade" id="modalEditarProveedor">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"
						aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<h4 class="modal-title">
						<strong>Editar Proveedor</strong>
					</h4>
				</div>
				<form role="form" method="post" action="" id="formActualizaProveedor">
					<div class="modal-body">
						<div class="form-group">
							<label for="nombreProveedorEdit">Nombre de Proveedor</label> <input
								id="nombreProveedorEdit" name="nombreProveedorEdit" type="text" class="form-control"
								placeholder="Proveedor">
						</div>
						
						
						
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-outline pull-left"
							data-dismiss="modal">
							<span class="fa fa-remove"></span>
						</button>
						<button type="submit" class="btn btn-outline">
							<span class="fa fa-check"></span>
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>
	<!-- Termina Modal Edita Proveedor -->

</section>