<div class="caja_formulario medida1 bg1 sombra1">
 <h1 class="ico_inicio">AREA DE ACCESO AL SISTEMA</h1>

	<div class="login">

		<form method="post" id="loginform" name="loginform"
			action="<?=$_SERVER['PHP_SELF']?>">


			<B>Ingresar al sistema</B><BR>

			<div class="campo">
					<label class="etiqueta" for="user">Usuario</label> 
					<input type="text" name="user" id="user"  size="40" required>
			</div>

			<div class="campo">
				<label class="etiqueta" for="pass">Contrase&ntilde;a</label> 
				<input type="password" name="pass" id="pass"  size="40" required>
			</div>
			<br />
			<div class="campo">
				<input type="submit" value="Entrar">
			</div>
		</form>

		<div style="color: red;">
			<?=$this->mensaje?>
		</div>
	</div>
</div>
