<section class="content-header">

	<h1>Boleteo</h1>

	<ol class="breadcrumb">
		<li><a href="/index.php/sistema/index"><i class="fa fa-line-chart"></i>
				Reportes</a></li>
		<li class="active">Reporte Boleteo</li>
	</ol>

</section>

<section class="content">

	<div class="box box-primary">

		<div class="box-header with-border">
			<h3 class="box-title">
				<strong>Buscar Boleteo</strong>
			</h3>
		</div>

		<form role="form" action="" id="formReporteBoleteo">

			<div class="row">
				<div class="col-md-6">
					<div class="box-body">

						<div class="form-group">
							<label for="carteraSelect">Cartera</label> <select
								class="form-control" id="carteraSelect" name="carteraSelect">
								<option value="">Seleccione</option>
								<option value="1">Ejecutivo</option>
								<option value="2">Cartera de Supervisor</option>
								<option value="3">Toda la empresa</option>
							</select>
						</div>

						<div class="form-group">
							<label for="nombreClientInput">Nombre Cliente</label> <input
								type="text" id="nombreClientInput" name="nombreClientInput"
								class="form-control" placeholder="Amanda L&oacute;pez">
						</div>

						<div class="form-group">
							<label for="cumplioMetaSelect">Cumpli&oacute; Meta</label> <select
								class="form-control" id="cumplioMetaSelect"
								name="cumplioMetaSelect">
								<option value="">Seleccione</option>
								<option value="1">Si</option>
								<option value="2">No</option>
							</select>
						</div>

					</div>
				</div>

				<div class="col-md-6">
					<div class="box-body">

						<div class="form-group">
							<label for="anioSelect">A&ntilde;o</label> <select
								class="form-control" id="anioSelect" name="anioSelect">
								<option value="">Seleccione</option>
								<option value="2020">2020</option>
								<option value="2019">2019</option>
								<option value="2018">2018</option>
								<option value="2017">2017</option>
								<option value="2016">2016</option>
								<option value="2015">2015</option>
								
							</select>
						</div>

						<div class="form-group">
							<label for="rutInput">Rut</label> <input class="form-control"
								type="text" id="rutInput" name="rutInput" maxlength="12"
								placeholder="12.345.678-0">
						</div>

						<div class="form-group">
							<label for="tipoPersonaSelect">Tipo Persona</label> <select
								class="form-control" id="tipoPersonaSelect" name="tipoPersonaSelect">
								<option value="">Seleccione</option>
								<option value="1">Natural</option>
								<option value="2">Jur&iacute;dica</option>
							</select>
						</div>

					</div>
				</div>

			</div>
			<div class="box-footer">
				<button type="submit" class="btn btn-success">
					Buscar <span class="fa fa-search"></span>
				</button>
			</div>

		</form>

	</div>

	<div class="box box-primary">

		<div class="box-header with-border">
			<h3 class="box-title">
				<strong>Resultados</strong>
			</h3>
		</div>


		<div class="row">
			<div class="col-md-12">
				<div class="box-body">
					<table class="table table-bordered table-hover cell-border compact"
						id="tableBoleteo">
						<thead>
							<th>Cliente</th>
							<th>N&uacute;mero Sociedad</th>
							<th>Rut</th>
							<th>Empresa / Persona Natural</th>
							<th>Meta</th>
							<th>Boleteo Acumulado</th>
							<th>%</th>
						</thead>
						<tbody>

							<tr>
								<td>Juan G&oacute;mez</td>
								<td></td>
								<td>12.345.678-9</td>
								<td>Persona Natural</td>
								<td>$1.000.000</td>
								<td>$800.000</td>
								<td>80%</td>
							</tr>

							<tr>
								<td>Daniel G&oacute;mez</td>
								<td></td>
								<td>12.345.678-9</td>
								<td>Persona Natural</td>
								<td>$1.000.000</td>
								<td>$800.000</td>
								<td>80%</td>
							</tr>

						</tbody>
					</table>
					<br />
				</div>

			</div>
		</div>
	</div>

</section>

<!---------- Ventanas Modales ---------->

<!-- Modal Rut Incorrecto -->
<div class="modal modal-danger fade" id="modalRutIncorrecto">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title">
					<strong>Atenci&oacute;n</strong>
				</h4>
			</div>
			<div class="modal-body">
				<p>El rut ingresado es incorrecto</p>
			</div>
			<div class="modal-footer">
				<button type="button" data-dismiss="modal" class="btn btn-outline">Ok</button>
			</div>
		</div>
	</div>
</div>
<!-- Termina Modal Rut Incorrecto -->


