<section class="content-header">
	<h1>Reporte Consolidado</h1>

	<ol class="breadcrumb">
		<li><a href="/index.php/sistema/index"><i class="fa fa-line-chart"></i>
				Reportes</a></li>
		<li class="active">Reporte Consolidado</li>
	</ol>

</section>

<section class="content">

	<!-- Sección Filtro Reporte -->
	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title">
				<strong>Filtro Reporte Consolidado</strong>
			</h3>
		</div>
		<form action="" method="post" id="formReporteConsolidado">

			<div class="box-body">
				<div class="form-group">
					<label>Seleccione una fecha de inicio y termino</label> <input
						type="text" placeholder="dd/mm/yyyy - dd/mm/yyyy"
						class="form-control pull-right" id="fechaDesdeHasta"
						name="fechaDesdeHasta">
				</div>
			</div>

			<div class="box-footer">
				<button id="buttonReporte" type="submit" class="btn btn-success">
					Buscar <span class="fa fa-search"></span>
				</button>
			</div>

		</form>
	</div>


	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title">
				<strong>DETALLE</strong>
			</h3>
		</div>

		<div class="box-body">
			<!-- Honorarios -->
			<div class="box box-success">
				<div class="box-header with-border">
					<h4 class="box-title">Honorarios</h4>
				</div>
				<div class="row">
					<div class="col-md-12">
						<table class="table compact">
							<tbody>
								<tr>
									<th>Honorarios del Periodo</th>
									<td>$123.456</td>
								</tr>
								<tr>
									<th>Honorarios periodos anteriores</th>
									<td>$123.456</td>
								</tr>
								<tr>
									<th>Honorarios por cobrar</th>
									<td>$123.456</td>
								</tr>
							</tbody>
							<tfoot>
								<tr>
									<th>Total Honorarios</th>
									<th class="alignRight">$123.456</th>
								</tr>
							</tfoot>
						</table>
					</div>
				</div>
			</div>
			<!-- Otros Ingresos -->
			<div class="box box-success">
				<div class="box-header with-border">
					<h4 class="box-title">Otros Ingresos</h4>
				</div>
				<div class="row">
					<div class="col-md-12">
						<table class="table compact">
							<tbody>
								<tr>
									<th>Otros Ingresos</th>
									<td>$123.456</td>
								</tr>
							</tbody>
							<tfoot>
								<tr>
									<th>Total otros ingresos</th>
									<th class="alignRight">$123.456</th>
								</tr>
							</tfoot>
						</table>
					</div>
				</div>
			</div>
			<!-- Saldos a Favor -->
			<div class="box box-success">
				<div class="box-header with-border">
					<h4 class="box-title">Saldo a Favor</h4>
				</div>
				<div class="row">
					<div class="col-md-12">
						<table class="table compact">
							<tbody>
								<tr>
									<th>Dineros Recibidos por Canje</th>
									<td>$123.456</td>
								</tr>
								<tr>
									<th>Dineros Emitidos Por Canje</th>
									<td>$123.456</td>
								</tr>
								<tr>
									<th>Saldo a favor clientes</th>
									<td>$123.456</td>
								</tr>
							</tbody>
							<tfoot>
								<tr>
									<th>Total a favor (contra)</th>
									<th class="alignRight">$123.456</th>
								</tr>
							</tfoot>
						</table>
					</div>
				</div>
			</div>
			<!-- Gastos de Administracion -->
			<div class="box box-success">
				<div class="box-header with-border">
					<h4 class="box-title">Gastos de Administraci&oacute;n</h4>
				</div>
				<div class="row">
					<div class="col-md-12">
						<table class="table compact">
							<tbody>
								<tr>
									<th>Gastos de Clientes</th>
									<td>$123.456</td>
								</tr>
								<tr>
									<th>Caja Chica</th>
									<td>$123.456</td>
								</tr>
								<tr>
									<th>Imposiciones Personal</th>
									<td>$123.456</td>
								</tr>
								<tr>
									<th>Boleta Honorarios</th>
									<td>$123.456</td>
								</tr>
								<tr>
									<th>Impuestos Angkor</th>
									<td>$123.456</td>
								</tr>
								<tr>
									<th>Proveedores Varios</th>
									<td>$123.456</td>
								</tr>
								<tr>
									<th>Rend Fondos</th>
									<td>$123.456</td>
								</tr>
								<tr>
									<th>Sueldos</th>
									<td>$123.456</td>
								</tr>
							</tbody>
							<tfoot>
								<tr>
									<th>Gastos de administraci&oacute;n</th>
									<th class="alignRight">$123.456</th>
								</tr>
							</tfoot>
						</table>
					</div>
				</div>
			</div>
		</div>
		<!-- Box Body -->
	</div>
	<!-- Box Primary -->

	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title">
				<strong>RESUMEN</strong>
			</h3>
		</div>

		<div class="box-body">
			<!-- Crecimiento Asignado al periodo -->
			<div class="box box-success">
				<div class="box-header with-border">
					<h4 class="box-title">Crecimiento Asignado al periodo</h4>
				</div>
				<div class="row">
					<div class="col-md-12">
						<table class="table compact">
							<tbody>
								<tr>
									<th>Honorarios del Periodo</th>
									<td>$123.456</td>
								</tr>
								<tr>
									<th>Otros Ingresos</th>
									<td>$123.456</td>
								</tr>
								<tr>
									<th>Gastos de Administraci&oacute;n</th>
									<td>$123.456</td>
								</tr>
							</tbody>
							<tfoot>
								<tr>
									<th>Suma Crecimiento</th>
									<th class="alignRight">$123.456</th>
								</tr>
							</tfoot>
						</table>
					</div>
				</div>
			</div>
			<!-- Dineros no correspondientes al periodo -->
			<div class="box box-success">
				<div class="box-header with-border">
					<h4 class="box-title">Dineros no correspondientes al periodo</h4>
				</div>
				<div class="row">
					<div class="col-md-12">
						<table class="table compact">
							<tbody>
								<tr>
									<th>Honorarios Periodos Anteriores</th>
									<td>$123.456</td>
								</tr>
								<tr>
									<th>Saldo a favor (contra)</th>
									<td>$123.456</td>
								</tr>
							</tbody>
							<tfoot>
								<tr>
									<th>Suma de Dineros no correspondientes al periodo anterior</th>
									<th class="alignRight">$123.456</th>
								</tr>
							</tfoot>
						</table>
					</div>
				</div>
			</div>
			<!-- Total Caja -->
			<div class="box box-success">
				<div class="box-header with-border">
					<h4 class="box-title">
						<strong>Total Caja</strong>
					</h4>
				</div>
				<div class="row">
					<div class="col-md-12">
						<table class="table compact">
							<tbody>
								<tr>
									<th>Crecimiento asignado al periodo</th>
									<td>$123.456</td>
								</tr>
								<tr>
									<th>Dineros no correspondiente al periodo</th>
									<td>$123.456</td>
								</tr>
								<tr>
									<th>Honorarios por cobrar</th>
									<td>$123.456</td>
								</tr>
							</tbody>
							<tfoot>
								<tr>
									<th>Total</th>
									<th class="alignRight">$123.456</th>
								</tr>
							</tfoot>
						</table>
					</div>
				</div>
			</div>
		</div>
		<!-- Box Body -->
	</div>
	<!-- Box Primary -->



</section>

<!---------- Ventanas Modales ---------->

<!-- Modal Rut Incorrecto -->
<div class="modal modal-danger fade" id="modalRutIncorrecto">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title">
					<strong>Atenci&oacute;n</strong>
				</h4>
			</div>
			<div class="modal-body">
				<p>El rut ingresado es incorrecto</p>
			</div>
			<div class="modal-footer">
				<button type="button" data-dismiss="modal" class="btn btn-outline">Ok</button>
			</div>
		</div>
	</div>
</div>
<!-- Termina Modal Rut Incorrecto -->