<section class="content-header">
          <h1>
            Reporte de Proyectos
            <small>Reporte de Proyectos por filtros</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Admin</a></li>
            <li class="active">Reporte Proyectos</li>
          </ol>
</section>
 <section class="content">
 
 <?php
 if(isset($this->msg))
 {	
 	
 	if($this->msg['valor'] == true)
 	{	
 ?>
		 <div class="row">
		            <div class="col-md-12">
		              <div class="box box-solid">
		                  <div class="alert alert-success alert-dismissable">
		                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		                    <h4>	<i class="icon fa fa-check"></i> Ingreso Correcto!</h4>
		                    <?=$this->msg['mensaje']?>
		                  </div>
		              </div><!-- /.box -->
		            </div><!-- /.col -->
		</div>
<?php 
 	}elseif($this->msg['valor'] == false)
 	{
?> 	
 		<div class="row">
            <div class="col-md-12">
              <div class="box box-solid">
                  <div class="alert alert-danger alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h4><i class="icon fa fa-ban"></i> Ingreso Incorrecto!</h4>
						<?=$this->msg['mensaje']?>
                    </div>
              </div><!-- /.box -->
            </div><!-- /.col -->
        </div>	
<?php  	
	}
 }
 ?>
 <!-- general form elements disabled -->
 <div class="row">
 <div class="col-xs-12">
	         <form role="form" method="post">

			<!----------------------------- -------------------------->
			
                   
			<div class="productos">
				<div class="box box-danger"><!-- collapsed-box si se quiere inicial con la caja cerrada -->
	                <div class="box-header">
	                  <h3 class="box-title">Seleccione los filtros deseados</h3>
	                  <div class="box-tools pull-right">
						<button class="btn btn-box-tool" data-widget="collapse">
							<i class="fa fa-minus"></i>
						</button>
					</div>
					<!-- /.box-tools -->
	                </div>
	                <div class="box-body">
	                  <!-- Date dd/mm/yyyy -->
	                  <div class="form-group">
								<label>Vendedor</label>
								
								<select name="vendedor" id="vendedor" class="form-control select2 vendedor" style="width: 100%;">
									<option value="" selected>Seleccione un Vendedor</option>
							    </select>
						
		              </div><!-- /.form-group -->
		              
	                  <div class="form-group">
								<label>L&iacute;nea de Negocios</label>
								
								<select name="lineadenegocios" id="lineadenegocios" class="form-control select2 lineadenegocios" style="width: 100%;" >
									<option value="" selected>Seleccione una Linea de Negocio</option>
							    </select>
						
		              </div><!-- /.form-group -->
	
	                  <div class="form-group">
								<label>Categor&iacute;a</label>
								<select name="categoria" id="categoria" class="form-control select2 categoria" style="width: 100%;" >
									<option value="" selected>Seleccione una Categoria</option>
							    </select>
								
		              </div><!-- /.form-group -->
		              
		              
	                  <div class="form-group">
								<label>Sub Categor&iacute;a</label>		
								
								<select name="subcategoria" id="subcategoria" class="form-control select2 subcategoria" style="width: 100%;" >
									<option value="" selected>Seleccione una Sub Categoria</option>
							    </select>								
		              </div><!-- /.form-group -->
	
	
	                </div><!-- /.box-body -->
	              </div><!-- /.box -->
	              
	             
	              
              </div><!-- /.productos -->


		</form>
		</div>
</div>		
<div class="row">
<div class="col-xs-12">
			  <div class="box-footer">
                    <button id="generar" type="button" class="btn btn-primary">Generar</button>
                    
              </div>
</div>    
</div>
<div class="row">
            <div class="col-xs-12">
              <div class="box">
                <div class="box-header">
                  <!--<h3 class="box-title">Informaci&oacute;n de Mis Proyectos</h3>-->
                </div><!-- /.box-header -->
                <div class="box-body">            
                  <!-- <table id="example1" class="table table-bordered table-hover">-->
                  <table id="example1" style="white-space: nowrap;" class="table collapsed table-bordered responsive nowrap" cellspacing="0" width="100%">
                  <!-- <table id="example1" class=" table table-striped table-hover dt-responsive" cellspacing="0" width="100%">-->                 
                    <thead>
                      <tr>
                      	  <th>Titulo Proyecto</th>
	                      <th>Descripci&oacute;n</th>
	                      <th>Fecha Creaci&oacute;n</th>
	                      <th>Vendedor</th>
	                      <th>Id Cliente</th>
	                      <th>Rut Cliente</th>
						  <th>Linea de Negocios</th>
						  <th>Categor&iacute;a</th>
						  <th>Sub Categor&iacute;a</th>
						  <th>D&iacute;as Sin Avance</th>
						  <th>Score</th>
						 
						  
                      </tr>
                      
                    </thead>

                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
</div><!-- /.row -->		
		
 </section>
  
              