<div class="login-box">
	<div class="login-logo">
		<a href="#"><img height="137" width="166"
			src="/images/logo_<?=$this->nombre_sitio?>.png"></a>
	</div>
	<!-- /.login-logo -->
	<div class="login-box-body">
		<p class="login-box-msg">Bienvenido a Angkor, ingresa tus datos para
			acceder al sistema.</p>

		<form method="post">
			<div class="form-group has-feedback">
				<input type="email" class="form-control" placeholder="Email"
					id="username" name="username" required="required" /> <span
					class="glyphicon glyphicon-envelope form-control-feedback"></span>
			</div>
			<div class="form-group has-feedback">
				<input type="password" class="form-control" placeholder="Password"
					id="password" name="password" required="required"/> <span
					class="glyphicon glyphicon-lock form-control-feedback"></span>
			</div>
			<div class="row">
				<div class="col-xs-8">
					<div class="checkbox icheck">
						<label> <input type="checkbox"> Recordarme
						</label>
					</div>
				</div>
				<!-- /.col -->
				<div class="col-xs-4">
					<button type="submit" class="btn btn-primary btn-block btn-flat">Ingresar</button>
				</div>
				<!-- /.col -->
			</div>
		</form>

		<!--  <a href="#">Olvid&eacute; Mi Contrase&ntilde;a</a><br>
        <a href="#" class="text-center">Crear Nueva Cuenta</a>
        -->

	</div>
	<!-- /.login-box-body -->
</div>
<!-- /.login-box -->
