<section class="content-header">

	<h1>Modificar impuesto &uacute;nico <?= $this->titulo ?>  </h1>

	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-money"></i> Cobros</a></li>
		<li class="active">Modificar Impuesto &Uacute;nico</li>
	</ol>
</section>

<section class="content">

	<!-- Busqueda de Clientes -->
	<div class="box box-primary">

		<div class="box-header with-border">
			<h3 class="box-title">
				<strong>Buscar Rut</strong>
			</h3>
		</div>

		<form action="" method="post" id="formBusquedaImpuesto">

			<div class="box-body">

				<div class="form-group">
					<label for="tipoCobroSelect">Tipo de Cobro</label> <select
						class="form-control" id="tipoCobroSelect" name="tipoCobroSelect">
						<option value="">Seleccione</option>
						<option value="1" selected>F29</option>
					</select>
				</div>

				<div class="form-group">
					<label for="ejecutivoSelect">Ejecutivo</label> <select
						class="form-control" id="ejecutivoSelect" name="ejecutivoSelect">
					</select> <strong class="hide" id="seleccioneEjecutivo"
						style="color: Crimson; padding: 0px; margin: 0px;">Debe
						seleccionar al ejecutivo</strong>

				</div>

				<div class="form-group">
					<label for="idClienteSelect">Clientes</label> <select
						class="form-control" id="idClienteSelect" name="idClienteSelect">
						<option value="">Seleccione</option>
					</select>
				</div>

				<div class="form-group">
					<label for="idRutSelect">RUT Asociados</label> <select
						class="form-control" id="idRutSelect" name="idRutSelect">
						<option value="">Seleccione</option>
					</select>
				</div>

				<div class="form-group" id="f29">
					<label for="dateCobroInput">Fecha de Cobro</label>
					<div class="input-group">
						<input class="form-control dateCobroF29" name="dateCobroInput"
							value="<?= $this->calendario ?>" data-provide="datepicker"
							type="text"> <span class="input-group-addon"><i
							class="fa fa-calendar"></i></span>
					</div>

				</div>

				<div class="form-group">

					<div class="alert alert-warning alert-dismissable hide"
						id="seleccioneEjecutivo">
						<button type="button" class="close" id="buttonSeleccioneEjecutivo"
							aria-hidden="true">&times;</button>
						<h4>
							<i class="icon fa fa-warning"></i> Ops !
						</h4>
						<p>Debe seleccionar el ejecutivo</p>
					</div>
					
					<?php
					if ($this->resultados == '0') {
						?>	
							<div class="alert alert-warning alert-dismissable" id="sinDatos">
						<?php
					} else {
						?>
							<div class="alert alert-warning alert-dismissable hide"
							id="sinDatos">
							<?php
					}
					
					?> 
							<h4>
								<i class="icon fa fa-warning"></i> Ops !
							</h4>
							<p>No se encontraron datos</p>
						</div>

					</div>

				</div>
				<div class="box-footer">
					<button type="submit" class="btn btn-primary">
						Buscar <span class="fa fa-search"></span>
					</button>
				</div>
		
		</form>
	</div>

	<!-- Tabla de Resultados Cobros Impuesto -->
	
	<?php 
	
		if($this->hideImpuesto=='0')
		{
			?>
				<div class="box box-primary" hidden="">
			<?php 
		}
		else
		{
			?>
				<div class="box box-primary">
			<?php 
		}
	
	?>
			<div class="box-header with-border">
				<h3 class="box-title">
					<strong>Listado impuesto &uacute;nico</strong>
				</h3>
			</div>

			<div class="box-body">
				<div class="row">

					<div class="col-md-12">

						<div class="form-group">
		
							<?=$this->tablaImpuesto;?>
							
						</div>

					</div>

				</div>

			</div>

			<div class="box-footer">
				<button type="button"  class="btn btn-success" id="buttonModificaImpuesto">
					Modificar <span class="fa fa-edit"></span>
				</button>
			</div>

		</div>
	
	<!-- Termina Tabla de Resultados Cobros Impuesto -->
		
</section>