<?php 

if(isset($this->mensaje)){
	echo $this->mensaje;
}

?>

<section class="content-header">

	<h1>Detalle de Cartola</h1>

	<ol class="breadcrumb">
		<li><a href="/index.php/sistema/index"><i class="fa fa-users"></i>
				Cartola</a></li>
		<li class="active">Detalle Cartola</li>
	</ol>

</section>

<section class="content">

<?php 

 if(isset($this->msg))
 {	
 	
 	if($this->msg['valor'] == true)
 	{	

?>
		 <div class="row">
		            <div class="col-md-12">
		              <div class="box box-solid">
		                  <div class="alert alert-success alert-dismissable">
		                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		                    <h4>	<i class="icon fa fa-check"></i> Carga Correcta!</h4>
		                    <?=$this->msg['mensaje']?>
		                  </div>
		              </div><!-- /.box -->
		            </div><!-- /.col -->
		</div>
<?php 
 	}elseif($this->msg['valor'] == false)
 	{
?> 	
 		<div class="row">
            <div class="col-md-12">
              <div class="box box-solid">
                  <div class="alert alert-danger alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h4><i class="icon fa fa-ban"></i> Problemas con la carga del archivo!</h4>
						<?=$this->msg['mensaje']?>
                    </div>
              </div><!-- /.box -->
            </div><!-- /.col -->
        </div>	
<?php  	
	}
 }


if(isset($this->detalle)){
?>
 
	<div class="box box-primary">

		<div class="box-header with-border">
			<h3 class="box-title">
				<strong>Detalle de movimientos de cartola</strong>
			</h3>
		</div>
			<table id="example1" class="table table-bordered responsive nowrap" cellspacing="0" width="100%">
			                  <!-- <table id="example1" class=" table table-striped table-hover dt-responsive" cellspacing="0" width="100%">-->                 
			                    <thead>
			                      <tr>
				                      <th>Id Detalle</th>
				                      <th>Id Cartola</th>
			                      	  <th>Fecha Movimiento</th>
			                      	  <th>Detalle Movimiento</th>
				                      <th>Cheque o Cargo</th>
				                      <th>Dep&oacute;sito o Abono</th>
				                      <th>Saldo</th>
				                      <th>Nro Documento</th>
				                      <th>Estado</th>
				                      <th>Monto Compensado</th>
				                      <th>Trn</th>
				                      <th>Caja</th>
				                      <th>Sucursal</th>
			                      </tr>
			                    </thead>
			                    <tbody>
<?php 
foreach($this->detalle as $key => $detalle)
{
?>                  
				     				<tr>
				                      	  <td><?=$detalle['ci17_idDetalleCartola']?></td>
				                      	  <td><?=$detalle['ci16_idcartola']?></td>
										  <td><?=$detalle['ci17_fechaMovimiento']?></td>
										  <td><?=$detalle['ci17_detalleMovimiento']?></td>
										  <td>$<?=number_format($detalle['ci17_cheque_cargo'],0,',','.')?></td>
										  <td>$<?=number_format($detalle['ci17_deposito_abono'],0,',','.')?></td>	
										  <td>$<?=number_format($detalle['ci17_saldo'],0,',','.')?></td>	
										  <td><?=$detalle['ci17_nroDocumento']?></td>
										  <td><?=$detalle['ci36_nombreEstado']?></td>	
										  <td>$<?=number_format($detalle['ci17_montoCompensado'],0,'','')?></td>		
										  <td><?=$detalle['ci17_trn']?></td>	
										  <td><?=$detalle['ci17_caja']?></td>	
										  <td><?=$detalle['ci17_sucursal']?></td>		 
				                    </tr>  
<?php 
}
?>     
			                    </tbody>
			                    </table>
	</div>
<?php 
}else{
?>	
 		<div class="row">
            <div class="col-md-12">
              <div class="box box-solid">
                  <div class="alert alert-danger alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h4><i class="icon fa fa-ban"></i> No se encuentra el detalle requerido</h4>
                    </div>
              </div><!-- /.box -->
            </div><!-- /.col -->
        </div>
<?php 
}
?>


</section>