<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title><?=$this->nombre_sitio?></title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.4 -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="/ionicons/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- DATA TABLES -->
    <!-- <link href="/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />-->
    <link href="/plugins/datatables/jquery.dataTables.css" rel="stylesheet" type="text/css" />
    
    
    <link href="/plugins/datatables/dataTables.responsive.css" rel="stylesheet" type="text/css" />
 
    <!-- Theme style -->
    <link href="/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link href="/dist/css/skins/<?=$this->skin?>.min.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
  <style>
  	.editar{
  		width:20px;
  		height:40px;
  		padding:0px;
  		margin:0px;
  	}
 

    
  </style>  
  </head>
  <!--
  BODY TAG OPTIONS:
  =================
  Apply one or more of the following classes to get the
  desired effect
  |---------------------------------------------------------|
  | SKINS         | skin-blue                               |
  |               | skin-black                              |
  |               | skin-purple                             |
  |               | skin-yellow                             |
  |               | skin-red                                |
  |               | skin-green                              |
  |---------------------------------------------------------|
  |LAYOUT OPTIONS | fixed                                   |
  |               | layout-boxed                            |
  |               | layout-top-nav                          |
  |               | sidebar-collapse                        |
  |               | sidebar-mini                            |
  |---------------------------------------------------------|
  -->
  <body class="<?=$this->skin?> sidebar-mini">
    <div class="wrapper">

      
  <!-- Main Header -->
      	<?=$this->render('head.phtml') ?>	
  <!-- Fin Main Header -->    	

      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">

          <!-- Sidebar user panel (optional) -->
				<?=$this->render('sidebaruserpanel.phtml') ?>	
		  <!-- Fin Sidebar user panel -->
		  
          <!-- Sidebar Menu -->
				<?=$this->render('menu.phtml') ?>		
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <!-- Main content -->
       
          <?=$this->layout()->content?>
       
        <!-- /.content -->
      </div><!-- /.content-wrapper -->

      <!-- Main Footer -->
			
			<?= $this->render('footer.phtml') ?>

      <!-- Control Sidebar -->
      <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
      <div class="control-sidebar-bg"></div>
    </div><!-- ./wrapper -->

    <!-- REQUIRED JS SCRIPTS -->

    <!-- jQuery 2.1.4 -->
    <script src="/plugins/jQuery/jQuery-2.1.4.min.js" type="text/javascript"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- DATA TABES SCRIPT -->
    <script src="/plugins/datatables/jquery.dataTables.min.js" type="text/javascript"></script>
    
    <script src="/plugins/datatables/dataTables.responsive.js" type="text/javascript"></script>
    
    <!-- <script src="/plugins/datatables/dataTables.bootstrap.min.js" type="text/javascript"></script>-->
    <!-- SlimScroll -->
    <script src="/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src="/plugins/fastclick/fastclick.min.js" type="text/javascript"></script>
    <!-- AdminLTE App -->
    <script src="/dist/js/app.min.js" type="text/javascript"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/dist/js/demo.js" type="text/javascript"></script>
    <!-- page script -->
    <script type="text/javascript">
$(function () {
          
      $("#example1").DataTable({
		"responsive":true,
		 "bLengthChange": false,
		 "bFilter": true,
		 "bInfo": true,
		 "bPaginate": true,
		 "bSort": true,
		"language": {
			"lengthMenu": "Desplegando _MENU_ registros por p&aacute;gina",
			"zeroRecords": "Nada encontrado - Lo sentimos",
			"info": "Mostrando p&aacute;gina _PAGE_ de _PAGES_",
			"infoEmpty": "No hay registros disponibles",
			"infoPostFix":    "",
			"thousands":      ",",
			"loadingRecords": "Cargando...",
			"processing":     "Procesando...",
			"search":         "Buscar:",
			"infoFiltered ": "(Filtrando de un total de _MAX_ registros)",
			"paginate": {
				"first":      "Primero",
				"last":       "&Uacute;ltimo",
				"next":       "Siguiente",
				"previous":   "Anterior"
				}
			}
		});
		
      });
    </script>
  </body>
</html>
