<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title><?=$this->nombre_sitio?></title>
<!-- Tell the browser to be responsive to screen width -->
<meta
	content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
	name="viewport">
<!-- Bootstrap 3.3.4 -->
<link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet"
	type="text/css" />
<!-- Font Awesome Icons -->
<link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet"
	type="text/css" />

<!-- daterange picker, estilos calendario -->
<link href="/plugins/daterangepicker/daterangepicker-bs3.css"
	rel="stylesheet" type="text/css" />
<link href="/plugins/datepicker/datepicker3.css" rel="stylesheet"
	type="text/css" />

<!-- Ionicons -->
<link href="/ionicons/css/ionicons.min.css" rel="stylesheet"
	type="text/css" />
<!-- DATA TABLES -->
<!-- <link href="/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />-->
<link href="/plugins/datatables/jquery.dataTables.css" rel="stylesheet"
	type="text/css" />
<link href="/plugins/datatables/dataTables.tableTools.css"
	rel="stylesheet">

<link href="/plugins/datatables/dataTables.responsive.css"
	rel="stylesheet" type="text/css" />

<!-- iCheck for checkboxes and radio inputs -->
<link href="../../plugins/iCheck/all.css" rel="stylesheet"
	type="text/css" />

<!-- Theme style -->
<link href="/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
<!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
<link href="/dist/css/skins/<?=$this->skin?>.min.css" rel="stylesheet"
	type="text/css" />

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

<style>
.editar {
	width: 20px;
	height: 40px;
	padding: 0px;
	margin: 0px;
}

.right {
	align: right;
}

#formMantenedorUF .error {
	color: Crimson
}

#formMantenedorTasa .error {
	color: Crimson
}

#formMantenedorRetencion .error {
	color: Crimson
}
</style>
</head>
<!--
  BODY TAG OPTIONS:
  =================
  Apply one or more of the following classes to get the
  desired effect
  |---------------------------------------------------------|
  | SKINS         | skin-blue                               |
  |               | skin-black                              |
  |               | skin-purple                             |
  |               | skin-yellow                             |
  |               | skin-red                                |
  |               | skin-green                              |
  |---------------------------------------------------------|
  |LAYOUT OPTIONS | fixed                                   |
  |               | layout-boxed                            |
  |               | layout-top-nav                          |
  |               | sidebar-collapse                        |
  |               | sidebar-mini                            |
  |---------------------------------------------------------|
  -->
<body class="<?=$this->skin?> sidebar-mini">
	<div class="wrapper">


		<!-- Main Header -->
      	<?=$this->render('head.phtml') ?>	
  <!-- Fin Main Header -->

		<!-- Left side column. contains the logo and sidebar -->
		<aside class="main-sidebar">

			<!-- sidebar: style can be found in sidebar.less -->
			<section class="sidebar">

				<!-- Sidebar user panel (optional) -->
				<?=$this->render('sidebaruserpanel.phtml') ?>	
		  <!-- Fin Sidebar user panel -->

				<!-- Sidebar Menu -->
				<?=$this->render('menu.phtml') ?>		
        </section>
			<!-- /.sidebar -->
		</aside>

		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			<!-- Main content -->
       
          <?=$this->layout()->content?>
       
        <!-- /.content -->
		</div>
		<!-- /.content-wrapper -->

		<!-- Main Footer -->
			
			<?= $this->render('footer.phtml')?>

      <!-- Control Sidebar -->
		<!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
		<div class="control-sidebar-bg"></div>
	</div>
	<!-- ./wrapper -->

	<!-- REQUIRED JS SCRIPTS -->

	<!-- jQuery 2.1.4 -->
	<script src="/plugins/jQuery/jQuery-2.1.4.min.js"
		type="text/javascript"></script>

	<!-- Script RUT -->
	<script src="/plugins/jQueryRut/jquery.Rut.js" type="text/javascript"></script>

	<!-- Bootstrap 3.3.2 JS -->
	<script src="/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<!-- DATA TABES SCRIPT -->
	<script src="/plugins/datatables/jquery.dataTables.min.js"
		type="text/javascript"></script>

	<script src="/plugins/datatables/dataTables.responsive.js"
		type="text/javascript"></script>

	<!-- <script src="/plugins/datatables/dataTables.bootstrap.min.js" type="text/javascript"></script>-->
	<!-- SlimScroll -->
	<script src="/plugins/slimScroll/jquery.slimscroll.min.js"
		type="text/javascript"></script>
	<!-- FastClick -->

	<script src="/plugins/datatables/fnReloadAjax.js" cache="false"></script>
	<script src="/plugins/datatables/dataTables.tableTools.js"
		cache="false"></script>

	<script src="/plugins/fastclick/fastclick.min.js"
		type="text/javascript"></script>
	<!-- AdminLTE App -->
	<script src="/dist/js/app.min.js" type="text/javascript"></script>
	<!-- AdminLTE for demo purposes -->
	<script src="/dist/js/demo.js" type="text/javascript"></script>

	<!-- Jquery Validate -->
	<script src="/plugins/jqueryvalidate/jquery.validate.min.js"
		type="text/javascript"></script>
	<script src="/plugins/jqueryvalidate/additional-methods.min.js"
		type="text/javascript"></script>
	<script src="/plugins/jqueryvalidate/messages_es.min.js"
		type="text/javascript"></script>

	<script src="/plugins/jqueryprettynumber/jquery.prettynumber.js"
		type="text/javascript"></script>

	<!-- JQUERY Number -->
	<script src="/plugins/jquerynumber/jquery.number.js"
		type="text/javascript"></script>

	<!-- page script -->


	<script type="text/javascript">
	$(function(){	

		//*************************** MANTENEDOR DE UF ***************************//	
		
		var anioUf = "";	
		var mesUf = "";

		var anioTasa = "";
		var mesTasa = "";

		var anioRentencion = "";
		var mesRentencion = "";

		$('#ufValorInput').number( true, 2,',','.' );
		$('#retencionValorInput').number( true, 2,',','.' );
		$('#tasaValorInput').number( true, 2,',','.' );

		//validacion del formulario mantenedor de uf.
		$('#formMantenedorUF').validate({
			debug:true,
			rules:{
				anioUFSelect:{
					required:true
				},
				mesUFSelect:{
					required:true
				},
				ufValorInput:{
					required:true
				}				
			},
			messages:{

				anioUFSelect:"Debe seleccionar una elemento de la lista",
				mesUFSelect:"Debe seleccionar una elemento de la lista",
				ufValorInput:"Debe ingresar el valor de la UF"
				
			},
			invalidHandler:function(event, validator){
				
			},	
			submitHandler:function(datos)
			{
				if(!parseInt($('#ufValorInput').val())<1)	
				{
					$('#valorNoPermitidoUf').addClass('hide');
					
					url="/index.php/valores/guardaruf";

					//obtengo los datos del formulario validado
					var datosUf = "valorUf="+$('#ufValorInput').val()+"&anioUf="+$('#anioUFSelect').val()+"&mesUf="+$('#mesUFSelect').val();                                               
					
					//ajax para enviar los datos al controler que registra uf.
					$.ajax({
					    url : url,					    
					    type: "POST",					   
					    data : datosUf,
					    success: function(datos)
					    {							
					    	if(datos.guardado[0]=='1')
							{
								//registro correcto					
								$('#valorUfGuardado').removeClass('hide');
								limpioControlUf();								
							}
					    	else if(datos.guardado[0]=='2')
					    	{			    		
					    		//no registró
					    		$('#valorUfProblemaGuardado').removeClass('hide'); 
					    		limpioControlUf();			    	
					    	}
					    	
					    },				    
					    error : function(xhr, status) {
					    	//no registró
				    		$('#valorUfProblemaGuardado').removeClass('hide'); 
				    		limpioControlUf();
					    }			    
					});
				}
				else
				{
					$('#valorNoPermitidoUf').removeClass('hide');
				}										
			}	
		});	

		$('#buttonValorNoPermitidoUf').on('click', function()
		{
			$('#valorNoPermitidoUf').addClass('hide');
		});

		//obtengo el valor de la uf segun el anio seleccionado,
		//y acciono el metodo de busqueda del valor de la uf
		$('#anioUFSelect').on('change',function(){
			anioUf=$('#anioUFSelect').val();

			if(mesUf!="")
			{
				obtenerValorUfByAnioMes(anioUf, mesUf);
			}			
		});

		//obtengo el valor de la uf segun el mes seleccionado,
		//y acciono el metodo de busqueda del valor de la uf
		$('#mesUFSelect').on('change',function(){

			mesUf=$('#mesUFSelect').val();
			
			if(anioUf!="")
			{
				obtenerValorUfByAnioMes(anioUf, mesUf);	
			}			
			
		});

		//funcion para modificar el valos de la uf si 
		//ya se encuentra el mes y anio registrados
		function obtenerValorUfByAnioMes(anio, mes)
		{
			url="/index.php/valores/obteneruf";

			//obtengo los datos del anio y mes del uf
			var datosAnioMes = "anioUf="+anio+"&mesUf="+mes;                                               
			
			//ajax para enviar los datos al controler que registra uf.
			$.ajax({
			    url : url,					    
			    type: "POST",					   
			    data : datosAnioMes,
			    success: function(datos)
			    {
				    if(datos.valoruf[0]!="")
					{					   						
			    		$('#ufValorInput').val(datos.valoruf[0]);
					}
				    else
				    {
				    	$('#ufValorInput').val('');
				    }
			    },				    
			    error : function(xhr, status) {			    	
			    }			    
			});
		}
		
		//botones para cerrar mensajes
		$('#buttonValorUfGuardado').on('click',function(){
			$('#valorUfGuardado').addClass('hide');
		});

		$('#buttonvalorUfProblemaGuardado').on('click',function(){
			$('#valorUfProblemaGuardado').addClass('hide'); 
		});

		
		//*************************** MANTENEDOR DE TASA ***************************//
			
		//valido formulario mantenedor de tasas	
		$('#formMantenedorTasa').validate({
			debug:true,
			rules:{

				anioTasaSelect:{
					required:true
				},
				mesTasaSelect:{
					required:true
				},
				tasaValorInput:{
					required:true
				}
				
			},
			messages:{
				anioTasaSelect:"Debe seleccionar un elemento de la lista",
				mesTasaSelect:"Debe seleccionar un elemento de la lista",
				tasaValorInput:"Debe ingresar el valor de la renta"
				
			},
			invalidHandler:function(event, validator){
				
			},	
			submitHandler:function(datos)
			{	

				if(!parseInt($('#tasaValorInput').val())<1)	
				{
					$('#valorNoPermitidoTasa').addClass('hide');
					
					url="/index.php/valores/guardartasa";

					//obtengo los datos del formulario validado
					var datosTasa = "anioTasa="+anioTasa+"&valorTasa="+$('#tasaValorInput').val()+"&mesTasa="+mesTasa;                                               
					
					//ajax para enviar los datos al controler que registra la tasa.
					$.ajax({
					    url : url,					    
					    type: "POST",					   
					    data : datosTasa,
					    success: function(datos)
					    {							
					    	if(datos.guardado[0]=='1')
							{														    		
					    		$('#valorTasaGuardado').removeClass('hide');
					    		limpioControlesTasa();
							}
					    	else if(datos.guardado[0]=='2')
					    	{			    		
					    		$('#valorTasaProblemaGuardado').removeClass('hide');
					    		limpioControlesTasa();			    	
					    	}
					    	
					    },				    
					    error : function(xhr, status) {
				    		$('#valorTasaProblemaGuardado').removeClass('hide');
				    		limpioControlesTasa();
					    }			    
					});
				}
				else
				{
					$('#valorNoPermitidoTasa').removeClass('hide');
				}
				
		
			}	
		});

		//botones para cerrar mensajes.
		$('#buttonValorNoPermitidoTasa').on('click',function()
		{
			$('#valorNoPermitidoTasa').addClass('hide');
		});
		
		$('#buttonValorTasaGuardado').on('click',function()
		{
			$('#valorTasaGuardado').addClass('hide');
		});

		$('#buttonValorTasaProblemaGuardado').on('click',function()
		{
			$('#valorTasaProblemaGuardado').addClass('hide');
		});
		
		//obtengo el valor de la tasa segun el anio y mes seleccionado,
		//y acciono el metodo de busqueda del valor de la tasa
		$('#mesTasaSelect').on('change',function(){
			
			mesTasa=$('#mesTasaSelect').val();	
					
			if(mesTasa!="")
			{
				obtenerValorTasaByAnioMes(anioTasa,mesTasa);
			}
				
		});

		$('#anioTasaSelect').on('change',function(){
			
			anioTasa=$('#anioTasaSelect').val();			

			if(mesTasa!="")
			{
				obtenerValorTasaByAnioMes(anioTasa,mesTasa);
			}			
				
		});

		//funcion para modificar el valor de la Tasa si 
		//ya se encuentra el anio registrado
		function obtenerValorTasaByAnioMes(anio,mes)
		{
			url="/index.php/valores/obtenertasa";

			//obtengo los datos del anio y mes de la tasa
			var datosAnioMes = "anioTasa="+anio+"&mesTasa="+mesTasa;                                               
			
			//ajax para enviar los datos al controler que registra uf.
			$.ajax({
			    url : url,					    
			    type: "POST",					   
			    data : datosAnioMes,
			    success: function(datos)
			    {
				    if(datos.valortasa!="")
					{					   						
			    		$('#tasaValorInput').val(datos.valortasa);
					}
				    else
				    {
				    	$('#tasaValorInput').val('');
				    }
			    },				    
			    error : function(xhr, status) {			    	
			    }			    
			});
		}		

		//*************************** MANTENEDOR DE RETENCIONES ***************************//

		$('#formMantenedorRetencion').validate({
			debug:true,
			rules:{
				anioRetencionSelect:{
					required:true
				},
				mesRetencionSelect:{
					required:true
				},
				retencionValorInput:{
					required:true
				}			
			},
			messages:{
				anioRetencionSelect:"Debe seleccionar un elemento de la lista",
				retencionValorInput:"Debe ingresar el valor de la retenci&oacute;n",
				mesRetencionSelect:"Debe seleccionar un elemento de la lista"
				
			},
			invalidHandler:function(event, validator){
				
			},	
			submitHandler:function(datos)
			{
				if(!parseInt($('#retencionValorInput').val())<1)	
				{	
					$('#valorNoPermitidoRenta').addClass('hide');
					
					url="/index.php/valores/guardaretencion";

					//obtengo los datos del formulario validado
					var datosRetencion = "anioRetencion="+anioRentencion+"&mesRetencion="+mesRentencion+"&valorRetencion="+$('#retencionValorInput').val();                                               
					
					//ajax para enviar los datos al controler que registra la retencion.
					$.ajax({
					    url : url,					    
					    type: "POST",					   
					    data : datosRetencion,
					    success: function(datos)
					    {							
					    	if(datos.guardado[0]=='1')
							{										
					    		$('#valorRetencionGuardado').removeClass('hide');
					    		limpioControlesRetencion();
					    		
							}
					    	else if(datos.guardado[0]=='2')
					    	{			    		
					    		$('#valorRetencionProblemaGuardado').removeClass('hide');  
					    		limpioControlesRetencion();
					    	}
					    	
					    },				    
					    error : function(xhr, status) {
					    	$('#valorRetencionProblemaGuardado').removeClass('hide');
					    	limpioControlesRetencion();
					    }			    
					});
				}
				else
				{
					$('#valorNoPermitidoRenta').removeClass('hide');
				}				
			}	
		});	

		//cierro mensajes 
		$('#buttonValorNoPermitidoRenta').on('click',function()
		{
			$('#valorNoPermitidoRenta').addClass('hide');
		});		
		
		$('#buttonValorRetencionGuardado').on('click',function()
		{
			$('#valorRetencionGuardado').addClass('hide');
		});

		$('#buttonValorRetencionProblemaGuardado').on('click',function()
		{
			$('#valorRetencionProblemaGuardado').addClass('hide');
		});
		
		//obtengo el valor de la retencion segun el anio y mes seleccionado,
		//y acciono el metodo de busqueda del valor de la retencion
		$('#anioRetencionSelect').on('change',function(){
			anioRentencion=$('#anioRetencionSelect').val();

			if(mesRentencion!="")
			{
				obtenerValorRetencionByAnioMes(anioRentencion, mesRentencion);
			}			
		});

		//obtengo el valor de la uf segun el mes seleccionado,
		//y acciono el metodo de busqueda del valor de la uf
		$('#mesRetencionSelect').on('change',function(){

			mesRentencion=$('#mesRetencionSelect').val();
			
			if(anioRentencion!="")
			{
				obtenerValorRetencionByAnioMes(anioRentencion, mesRentencion);	
			}			
			
		});
		
		//funcion para modificar el valor de la Retencion si 
		//ya se encuentra el anio y mes registrado
		function obtenerValorRetencionByAnioMes(anio)
		{
			url="/index.php/valores/obtenerretencion";

			//obtengo los datos del anio y mes del uf
			var datosAnioMes = "anioRetencion="+anioRentencion+"&mesRetencion="+mesRentencion;                                               
			
			//ajax para enviar los datos al controler que registra uf.
			$.ajax({
			    url : url,					    
			    type: "POST",					   
			    data : datosAnioMes,
			    success: function(datos)
			    {
				    if(datos.valorretencion!="")
					{				   						
			    		$('#retencionValorInput').val(datos.valorretencion);
					}
				    else
				    {
				    	$('#retencionValorInput').val('');
				    }
			    },				    
			    error : function(xhr, status) {			    	
			    }			    
			});
		}	

		function limpioControlesRetencion()
		{
			$('#anioRetencionSelect').val('');
    		$('#mesRetencionSelect').val('');
    		$('#retencionValorInput').val('');
    		mesRentencion="";
    		anioRentencion="";
		}

		function limpioControlesTasa()
		{
			$('#anioTasaSelect').val('');
    		$('#tasaValorInput').val('');
    		$('#mesTasaSelect').val('');
    		anioTasa="";
    		mesTasa="";
		}

		function limpioControlUf()
		{
			anioUf = "";	
			mesUf = "";
			$('#ufValorInput').val('');
			$('#anioUFSelect').val('');
			$('#mesUFSelect').val('');	
		}	
		
		
	});
	</script>



</body>
</html>
