<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title><?=$this->nombre_sitio?></title>
<!-- Tell the browser to be responsive to screen width -->
<meta
	content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
	name="viewport">
<!-- Select2 -->
<link rel="stylesheet" href="../../plugins/select2/select2.min.css">
<!-- Bootstrap 3.3.4 -->
<link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet"
	type="text/css" />
<!-- Font Awesome Icons -->
<link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet"
	type="text/css" />
<!-- Ionicons -->
<link href="/ionicons/css/ionicons.min.css" rel="stylesheet"
	type="text/css" />
<!-- datepicker, estilos calendario -->
<link href="/plugins/datepicker/datepicker3.css" rel="stylesheet"
	type="text/css" />

<!-- DateRangePicker -->
<link href="/plugins/daterangepicker/daterangepicker-bs3.css"
	rel="stylesheet" type="text/css" />

<!-- DATA TABLES -->
<!-- <link href="/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />-->
<link href="/plugins/datatables/jquery.dataTables.css" rel="stylesheet"
	type="text/css" />
<link href="/plugins/datatables/dataTables.tableTools.css"
	rel="stylesheet">

<link href="/plugins/datatables/dataTables.responsive.css"
	rel="stylesheet" type="text/css" />

<!-- iCheck for checkboxes and radio inputs -->
<link href="../../plugins/iCheck/all.css" rel="stylesheet"
	type="text/css" />

<!-- Theme style -->
<link href="/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
<!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
<link href="/dist/css/skins/<?=$this->skin?>.min.css" rel="stylesheet"
	type="text/css" />

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

<style>
.editar {
	width: 20px;
	height: 40px;
	padding: 0px;
	margin: 0px;
}

#formBuscarOrdenPago .error {
	color: Crimson
}

#formVerificaPagoFolio .error {
	color: white
}
</style>
</head>
<!--
  BODY TAG OPTIONS:
  =================
  Apply one or more of the following classes to get the
  desired effect
  |---------------------------------------------------------|
  | SKINS         | skin-blue                               |
  |               | skin-black                              |
  |               | skin-purple                             |
  |               | skin-yellow                             |
  |               | skin-red                                |
  |               | skin-green                              |
  |---------------------------------------------------------|
  |LAYOUT OPTIONS | fixed                                   |
  |               | layout-boxed                            |
  |               | layout-top-nav                          |
  |               | sidebar-collapse                        |
  |               | sidebar-mini                            |
  |---------------------------------------------------------|
  -->
<body class="<?=$this->skin?> sidebar-mini">
	<div class="wrapper">


		<!-- Main Header -->
      	<?=$this->render('head.phtml') ?>	
  <!-- Fin Main Header -->

		<!-- Left side column. contains the logo and sidebar -->
		<aside class="main-sidebar">

			<!-- sidebar: style can be found in sidebar.less -->
			<section class="sidebar">

				<!-- Sidebar user panel (optional) -->
				<?=$this->render('sidebaruserpanel.phtml') ?>	
		  <!-- Fin Sidebar user panel -->

				<!-- Sidebar Menu -->
				<?=$this->render('menu.phtml') ?>		
        </section>
			<!-- /.sidebar -->
		</aside>

		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			<!-- Main content -->
       
          <?=$this->layout()->content?>
       
        <!-- /.content -->
		</div>
		<!-- /.content-wrapper -->

		<!-- Main Footer -->
			
			<?= $this->render('footer.phtml')?>

      <!-- Control Sidebar -->
		<!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
		<div class="control-sidebar-bg"></div>
	</div>
	<!-- ./wrapper -->

	<!-- REQUIRED JS SCRIPTS -->

	<!-- jQuery 2.1.4 -->
	<script src="/plugins/jQuery/jQuery-2.1.4.min.js"
		type="text/javascript"></script>

	<!-- Script RUT -->
	<script src="/plugins/jQueryRut/jquery.Rut.js" type="text/javascript"></script>

	<!-- Bootstrap 3.3.2 JS -->
	<script src="/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<!-- DATA TABES SCRIPT -->
	<script src="/plugins/datatables/jquery.dataTables.min.js"
		type="text/javascript"></script>

	<script src="/plugins/datatables/dataTables.responsive.js"
		type="text/javascript"></script>

	<!-- <script src="/plugins/datatables/dataTables.bootstrap.min.js" type="text/javascript"></script>-->
	<!-- SlimScroll -->
	<script src="/plugins/slimScroll/jquery.slimscroll.min.js"
		type="text/javascript"></script>
	<!-- FastClick -->

	<script src="/plugins/datatables/fnReloadAjax.js" cache="false"></script>
	<script src="/plugins/datatables/dataTables.tableTools.js"
		cache="false"></script>

	<script src="/plugins/fastclick/fastclick.min.js"
		type="text/javascript"></script>
	<!-- AdminLTE App -->
	<script src="/dist/js/app.min.js" type="text/javascript"></script>
	<!-- AdminLTE for demo purposes -->
	<script src="/dist/js/demo.js" type="text/javascript"></script>

	<!-- date-picker -->
	<script src="/plugins/datepicker/bootstrap-datepicker.js"
		type="text/javascript"></script>

	<!-- date-range-picker -->

	<script src="/plugins/daterangepicker/moment.js" type="text/javascript"></script>
	<script src="/plugins/daterangepicker/daterangepicker.js"
		type="text/javascript"></script>

	<!-- iCheck 1.0.1 Script checkbox y radiobuttons -->
	<script src="../../plugins/iCheck/icheck.min.js" type="text/javascript"></script>

	<!-- Script para validar numeros -->
	<script src="/plugins/jquerynumeric/jquery.numeric.js"
		type="text/javascript"></script>

	<!-- Jquery Validate -->
	<script src="/plugins/jqueryvalidate/jquery.validate.min.js"
		type="text/javascript"></script>
	<script src="/plugins/jqueryvalidate/additional-methods.min.js"
		type="text/javascript"></script>
	<script src="/plugins/jqueryvalidate/messages_es.min.js"
		type="text/javascript"></script>
	<!-- Select2 -->
	<script src="../../plugins/select2/select2.full.min.js"></script>

	<!-- page script -->
	<script type="text/javascript">
		$(function(){

			obtenerEjecutivos('#ejecutivoOrdenPagoSelect');

			var tablaVerificaPagos=$('#tablaVerificarPagos').dataTable( {
		        dom: 'T<"clear">lfrtip',
		        bFilter: false,
		        "responsive":true,
		        "searching":true,
		        "bLengthChange": false,
		        "autoWidth": false,
		        tableTools: {
		            "sSwfPath": "/swf/copy_csv_xls_pdf.swf",
		            "sRowSelect": "single",
		            "aButtons": [  ]
		        },
		        "language": {
					"lengthMenu": "Desplegando _MENU_ registros por p&aacute;gina",
					"zeroRecords": "Nada encontrado - Lo sentimos",
					"info": "Mostrando p&aacute;gina _PAGE_ de _PAGES_",
					"infoEmpty": "No hay registros disponibles",
					"infoPostFix":    "",
					"thousands":      ",",
					"loadingRecords": "Cargando...",
					"processing":     "Procesando...",
					"search":         "Buscar:",
					"infoFiltered ": "(Filtrando de un total de _MAX_ registros)",
					"paginate": {
						"first":      "Primero",
						"last":       "&Uacute;ltimo",
						"next":       "Siguiente",
						"previous":   "Anterior"
						}
					}    
		    } );

			var id_user = '<?= $this->id_usuario ?>';
			var perfil=<?= $this->rol ?>;
			
			switch(perfil)
			{
				case 1:	
						$('#ejecutivoOrdenPagoSelect').val(id_user);
						$('#ejecutivoOrdenPagoSelect').attr({"disabled":true});
						obtenerClientesByjecutivo('#clienteVerificaPagoSelect',$('#ejecutivoOrdenPagoSelect').val());

						url = "/index.php/pago/obtenerordenespago?idCliente=&idRut=&fechaInicio=&fechaFinal=&idUsuario="+$('#ejecutivoOrdenPagoSelect').val();
						  
						tablaVerificaPagos.fnClearTable();				
						tablaVerificaPagos.fnReloadAjax(url);
				break;
				
			}	


			listarOrdenDePago();	
			
			$('#ejecutivoOrdenPagoSelect').select2();
			$('#clienteVerificaPagoSelect').select2();
			$('#rutVerificaPagoSelect').select2();	

			$('#formBuscarOrdenPago').validate({
				debug:true,
				rules:{
					ejecutivoOrdenPagoSelect:{
							required:false
					},
					clienteVerificaPagoSelect:{
							required:false
					},
					clienteOrdenPagoSelect:{
							required:false	
					},
					rutVerificaPagoSelect:{
							required:false	
					},
					fechaDesdeHasta:{
							required:false	
					}
				},
				messages:{
					ejecutivoOrdenPagoSelect:"Debe seleccionar une elemento de la lista",
					clienteVerificaPagoSelect:"Debe seleccionar un elemento de la lista",
					clienteOrdenPagoSelect:"Debe seleccionar un elemento de la lista",
					rutVerificaPagoSelect:"Debe seleccionar un elemento de la lista",
					fechaDesdeHasta:"Debe ingresar el rango de fechas"
				},
				invalidHandler:function(event, validator){
					
				},	
				submitHandler:function(datos)
				{	
					listarOrdenDePago();								
				}	
			});

			$('#formVerificaPagoFolio').validate({
				debug:true,
				rules:{
					folioPago:{
						required:true
					}			
				},
				messages:{
					folioPago:"Debe ingresar el n&uacute;mero de folio"
				},
				invalidHandler:function(event, validator)
				{
					
				},	
				submitHandler:function(datos)
				{					
					url="/index.php/pago/registrarfolio";

					datos="idPago="+obtenerIdPago()+
						  "&idCobro="+obtenerIdCobro()+
						  "&tipoCobro="+tipoCobro()+
						  "&folio="+$('#folioPago').val();
					
					$.ajax({
					    url: url,  
					    type: "POST",
					    data: datos,  
					    async:false,
					    success: function(datos)
					    {
						   if(datos.registro[0]=='1')
						   {
							   $('#registroNumeroFolio').removeClass('hide');
							   $('#modalVerificaOrdenPago').modal('hide');
							   listarOrdenDePago();							   
						   }
						   else if(datos.registro[0]=='2')
						   {
							   $('#errorAccion').removeClass('hide');
							   $('#modalVerificaOrdenPago').modal('hide');
						   }
					    },
					    error:function(status)
					    {
					    	 $('#errorAccion').removeClass('hide');
					    	 $('#modalVerificaOrdenPago').modal('hide');
					    }
					}); 	
				}
			});

			$('#buttonRegistroNumeroFolio').on('click',function()
			{
				$('#registroNumeroFolio').addClass('hide');
			});

			$('#buttonErrorAccion').on('click',function()
			{
				$('#errorAccion').addClass('hide');
			});

			$('#verificaOrdenPago').on('click',function()
			{				
				
				if(!estadoCobro())
				{
					if($('#tablaVerificarPagos tbody tr').hasClass('selected'))
					{					
						$('#modalVerificaOrdenPago').modal();
						$('#folioPago').val('');
					}
					else
					{
						$('#mensajeSeleccioneCobro').removeClass('hide');
					}
				}
				else
				{
					$('#mensajeCobroVerificado').removeClass('hide');
				}
										
			});

			$('#buttonMensajeMontosNoIguales').on('click',function()
			{
				$('#mensajeMontosNoIguales').addClass('hide');
			});

			$('#buttonMensajeCobroVerificado').on('click',function()
			{
				$('#mensajeCobroVerificado').addClass('hide');
			});

			$('#buttonMensajeSeleccioneCobro').on('click',function()
			{
				$('#mensajeSeleccioneCobro').addClass('hide');
			});

			$('#ejecutivoOrdenPagoSelect').on('change',function()
			{
				obtenerClientesByjecutivo('#clienteVerificaPagoSelect',$('#ejecutivoOrdenPagoSelect').val());

				if($('#ejecutivoOrdenPagoSelect').val()=='')
				{
					$('#rutVerificaPagoSelect').val('');
				}
			});

			$('#clienteVerificaPagoSelect').on('change',function()
			{
				obtenerRutCliente('#rutVerificaPagoSelect',$('#clienteVerificaPagoSelect').val());
			});					

		    $('#fechaDesdeHasta').daterangepicker(); 

		    function obtenerEjecutivos(objetivo)
			{				
			    url = '/index.php/usuario/listar';
			    
				$(objetivo).empty();			
						
				$('<option>').
				attr({value:""}).
				text('Seleccione').
				prop({disabled: false}).
				appendTo(objetivo);

				var dato="";
			
				$.ajax({
				    url: url,  
				    type: "POST",
				    data: dato,  
				    async:false,
				    success: function(datos){
					    
				    	 $.each(datos.data, function( index, value ) {
								
							 $('<option>').
							   prop({value:value[0]}).
							   text(value[1]).
							   appendTo(objetivo);
						});	
				    }
				}); 			
			} 	

		    function obtenerClientesByjecutivo(objetivo,idEjecutivo)
			{				
			    url = '/index.php/cliente/listarbyejecutivo?idUsuario='+idEjecutivo;
			    
				$(objetivo).empty();			
						
				$('<option>').
				attr({value:""}).
				text('Seleccione').
				prop({disabled: false}).
				appendTo(objetivo);

				var dato="";
			
				$.ajax({
				    url: url,  
				    type: "POST",
				    data: dato,  
				    async:false,
				    success: function(datos){
					    
				    	 $.each(datos.data, function( index, value ) {
								
							 $('<option>').
							   prop({value:value[0]}).
							   text(value[1]).
							   appendTo(objetivo);
						});	
				    }
				}); 			
			} 	

		    function obtenerRutCliente(objetivo,idCliente)
			{				
			    url = '/index.php/rut/listadorutbyidcliente';
			    						
			    $(objetivo).empty();			
				
				$('<option>').
				attr({value:""}).
				text('Seleccione').
				prop({disabled: false}).
				appendTo(objetivo);

				var dato="idCliente="+idCliente;
			
				$.ajax({
				    url: url,  
				    type: "POST",
				    data: dato,  
				    async:false,
				    success: function(datos){

				    	 $.each(datos.data, function( index, value ) {

				    		 var detalle=value[3]+" - "+value[1];
									
							 $('<option>').
							   prop({value:value[0]}).
							   text(detalle).
							   appendTo(objetivo);
						});	
					    
				    }
				}); 
				
			  }	

			//obtengo las ordenes de pago, asociados al cliente.
		    function listarOrdenDePago()
			{
		    	var dataInicio="";
		    	var inicioSplit="";
		    	var dataFinal="";
		    	var finalSplit="";

		    	var fechaInicio="";
		    	var fechaFinal="";
				
				if($('#fechaDesdeHasta').val()!='')
				{
					var data=$('#fechaDesdeHasta').val().split('-');	
					
					//obtengo fecha incial
					dataInicio=$.trim(data[0]);
					inicioSplit=dataInicio.split('/');				
	
					//obtengo la fecha final		
					dataFinal=$.trim(data[1]);
					finalSplit=dataFinal.split('/');	

					fechaInicio=inicioSplit[2]+"-"+inicioSplit[1]+"-"+inicioSplit[0];
					fechaFinal=finalSplit[2]+"-"+finalSplit[1]+"-"+finalSplit[0];
				}
				
				
				url = '/index.php/pago/obtenerordenespago?idCliente='+
					  $('#clienteVerificaPagoSelect').val()+
					  "&idRut="+$('#rutVerificaPagoSelect').val()+
					  "&fechaInicio="+fechaInicio+
					  "&fechaFinal="+fechaFinal+
					  "&idUsuario="+$('#ejecutivoOrdenPagoSelect').val();
				  
				tablaVerificaPagos.fnClearTable();				
				tablaVerificaPagos.fnReloadAjax(url);
			}

		    //funcion para obtener el id cobro asociado al rut.
		    function obtenerIdCobro()
			{
				var id="";			
					$('#tablaVerificarPagos').find('tr.selected').each(function(){
						id=$(this).find('td:first').html();				
					});
				return id;
			}

		    //me indica si el cobro que estoy modificando es honorario o cobroindividual
			//ya que las tablas para los honorarios y cobros indivudlaes estan sepradas.
			function tipoCobro()
			{
				var tipo="";			
				$('#tablaVerificarPagos').find('tr.selected').each(function(){
					tipo=$(this).find('td:first').next().html();		
					if(tipo=="Masivo")
					{
						id="1";
					}
					else
					{
						id="2";
					}
							
				});
			return id;
			}	

		    function obtenerIdPago()
			{
				var id="";			
					$('#tablaVerificarPagos').find('tr.selected').each(function(){
						id=$(this).find('td:first').next().next().html();				
					});
				return id;
			}

		    function estadoCobro()
			{
				var condicion=false;	
						
					$('#tablaVerificarPagos').find('tr.selected').each(function(){
						estado=$(this).find('td:first').next().next().next().next().next().next().next().next().next().next().html();				

						if(estado=='verificado')
						{
							condicion=true;
						}					

					});
				return condicion;
			}

		    function verificarMontos()
			{
				var estado=false;
				
				$('#tablaVerificarPagos').find('tr.selected').each(function()
				{
					cobrado=$.trim($(this).find('td:first').next().next().next().next().next().next().html().toString().replace('$ ',''));
								
					recibido=$.trim($(this).find('td:first').next().next().next().next().next().next().next().html().toString().replace('$ ',''));	

					if(recibido=='')
					{
						recibido=0;
					}
					
					if(cobrado=='')
					{
						cobrado=0;
					}					
					
					if(parseInt(recibido)<parseInt(cobrado))
					{
						estado=true;
					}						
				});
				
				return estado;
			}
		});

	</script>


</body>
</html>
