<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title><?=$this->nombre_sitio?></title>
<!-- Tell the browser to be responsive to screen width -->
<meta
	content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
	name="viewport">
<!-- Bootstrap 3.3.4 -->
<link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet"
	type="text/css" />
<!-- Font Awesome Icons -->
<link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet"
	type="text/css" />

<!-- daterange picker, estilos calendario -->
<link href="/plugins/daterangepicker/daterangepicker-bs3.css"
	rel="stylesheet" type="text/css" />
<link href="/plugins/datepicker/datepicker3.css" rel="stylesheet"
	type="text/css" />

<!-- Ionicons -->
<link href="/ionicons/css/ionicons.min.css" rel="stylesheet"
	type="text/css" />
<!-- DATA TABLES -->
<!-- <link href="/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />-->
<link href="/plugins/datatables/jquery.dataTables.css" rel="stylesheet"
	type="text/css" />
<link href="/plugins/datatables/dataTables.tableTools.css"
	rel="stylesheet">

<link href="/plugins/datatables/dataTables.responsive.css"
	rel="stylesheet" type="text/css" />

<!-- iCheck for checkboxes and radio inputs -->
<link href="../../plugins/iCheck/all.css" rel="stylesheet"
	type="text/css" />

<!-- Theme style -->
<link href="/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
<!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
<link href="/dist/css/skins/<?=$this->skin?>.min.css" rel="stylesheet"
	type="text/css" />

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

<style>
.editar {
	width: 20px;
	height: 40px;
	padding: 0px;
	margin: 0px;
}

.right {
	align: right;
}

#formMantenedorSociedades .error {
	color: Crimson
}

</style>
</head>
<!--
  BODY TAG OPTIONS:
  =================
  Apply one or more of the following classes to get the
  desired effect
  |---------------------------------------------------------|
  | SKINS         | skin-blue                               |
  |               | skin-black                              |
  |               | skin-purple                             |
  |               | skin-yellow                             |
  |               | skin-red                                |
  |               | skin-green                              |
  |---------------------------------------------------------|
  |LAYOUT OPTIONS | fixed                                   |
  |               | layout-boxed                            |
  |               | layout-top-nav                          |
  |               | sidebar-collapse                        |
  |               | sidebar-mini                            |
  |---------------------------------------------------------|
  -->
<body class="<?=$this->skin?> sidebar-mini">
	<div class="wrapper">


		<!-- Main Header -->
      	<?=$this->render('head.phtml') ?>	
  <!-- Fin Main Header -->

		<!-- Left side column. contains the logo and sidebar -->
		<aside class="main-sidebar">

			<!-- sidebar: style can be found in sidebar.less -->
			<section class="sidebar">

				<!-- Sidebar user panel (optional) -->
				<?=$this->render('sidebaruserpanel.phtml') ?>	
		  <!-- Fin Sidebar user panel -->

				<!-- Sidebar Menu -->
				<?=$this->render('menu.phtml') ?>		
        </section>
			<!-- /.sidebar -->
		</aside>

		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			<!-- Main content -->
       
          <?=$this->layout()->content?>
       
        <!-- /.content -->
		</div>
		<!-- /.content-wrapper -->

		<!-- Main Footer -->
			
			<?= $this->render('footer.phtml')?>

      <!-- Control Sidebar -->
		<!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
		<div class="control-sidebar-bg"></div>
	</div>
	<!-- ./wrapper -->

	<!-- REQUIRED JS SCRIPTS -->

	<!-- jQuery 2.1.4 -->
	<script src="/plugins/jQuery/jQuery-2.1.4.min.js"
		type="text/javascript"></script>

	<!-- Script RUT -->
	<script src="/plugins/jQueryRut/jquery.Rut.js" type="text/javascript"></script>

	<!-- Bootstrap 3.3.2 JS -->
	<script src="/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<!-- DATA TABES SCRIPT -->
	<script src="/plugins/datatables/jquery.dataTables.min.js"
		type="text/javascript"></script>

	<script src="/plugins/datatables/dataTables.responsive.js"
		type="text/javascript"></script>

	<!-- <script src="/plugins/datatables/dataTables.bootstrap.min.js" type="text/javascript"></script>-->
	<!-- SlimScroll -->
	<script src="/plugins/slimScroll/jquery.slimscroll.min.js"
		type="text/javascript"></script>
	<!-- FastClick -->

	<script src="/plugins/datatables/fnReloadAjax.js" cache="false"></script>
	<script src="/plugins/datatables/dataTables.tableTools.js"
		cache="false"></script>

	<script src="/plugins/fastclick/fastclick.min.js"
		type="text/javascript"></script>
	<!-- AdminLTE App -->
	<script src="/dist/js/app.min.js" type="text/javascript"></script>
	<!-- AdminLTE for demo purposes -->
	<script src="/dist/js/demo.js" type="text/javascript"></script>

	<!-- Script Solo Numeros  -->
	<script type="text/javascript"
		src="/plugins/jquerynumeric/jquery.numeric.js"></script>

	<!-- Jquery Validate -->
	<script src="/plugins/jqueryvalidate/jquery.validate.min.js"
		type="text/javascript"></script>
	<script src="/plugins/jqueryvalidate/additional-methods.min.js"
		type="text/javascript"></script>
	<script src="/plugins/jqueryvalidate/messages_es.min.js"
		type="text/javascript"></script>

	<script src="/plugins/jqueryprettynumber/jquery.prettynumber.js"
		type="text/javascript"></script>

	<!-- page script -->


	<script type="text/javascript">
	$(function(){	

		obtenerSociedades('#tipoSociedadSelect');
		
		//validacion del formulario mantenedor de uf.
		$('#formMantenedorSociedades').validate({
			debug:true,
			rules:{
				tipoSociedadSelect:{
					required:true
				},
				valorImpuestoSociedadInput:{
					required:true
				}			
			},
			messages:{
				tipoSociedadSelect:"Debe seleccionar una elemento de la lista",
				valorImpuestoSociedadInput:"Debe ingresar el valor del impuesto",				
			},
			invalidHandler:function(event, validator)
			{
				
			},	
			submitHandler:function(datos)
			{	
				url="/index.php/sociedad/registrar";

				//obtengo los datos del formulario validado
				var datosSociedad = "idSociedad="+$('#tipoSociedadSelect').val()+"&impuestoSociedad="+$('#valorImpuestoSociedadInput').val();                                               
				
				//ajax para enviar los datos al controler que guarda el impuesto.
				$.ajax({
				    url : url,					    
				    type: "POST",					   
				    data : datosSociedad,
				    success: function(datos)
				    {							
				    	if(datos.guardado[0]=='1')
						{
							//registro correcto					
							$('#valorSociedadGuardado').removeClass('hide');
							limpiarControles()													
						}
				    	else if(datos.guardado[0]=='2')
				    	{			    		
				    		//no registró
				    		$('#valorSociedadProblemaGuardado').removeClass('hide'); 
				    		limpiarControles()
				    	}
				    	
				    },				    
				    error : function(xhr, status) {
				    	//no registró
			    		$('#valorSociedadProblemaGuardado').removeClass('hide'); 
			    		limpiarControles()
				    }			    
				});
										
			}	
		});	

		$('#buttonValorSociedadGuardado').on('click',function()
		{
			$('#valorSociedadGuardado').addClass('hide');
		});

		$('#buttonValorSociedadProblemaGuardado').on('click',function()
		{
			$('#valorSociedadProblemaGuardado').addClass('hide');
		});

		//obtengo el valor del impuesto segun el tipo de sociedad seleccionado,
		//y acciono el metodo de busqueda del valor
		$('#tipoSociedadSelect').on('change',function()
		{
			if($('#tipoSociedadSelect').val()!='')
			{
				obtenerValorSociedadById($('#tipoSociedadSelect').val());
			}
			else
			{
				$('#valorImpuestoSociedadInput').val('');
			}
			
		});	

		$('#valorImpuestoSociedadInput').numeric('.');	

		//funcion para modificar el valos de la uf si 
		//ya se encuentra el mes y anio registrados
		function obtenerValorSociedadById(id)
		{
			url="/index.php/sociedad/obtenervalorsociedad";

			//obtengo los datos del anio y mes del uf
			var datosSociedad = "idSociedad="+id;                                               
			
			//ajax para enviar los datos al controler que registra uf.
			$.ajax({
			    url : url,					    
			    type: "POST",					   
			    data : datosSociedad,
			    success: function(datos)
			    {
				    if(datos.valorsociedad[0]!="")
					{					   						
			    		$('#valorImpuestoSociedadInput').val(datos.valorsociedad[0]);
					}
				    else
				    {
				    	$('#valorImpuestoSociedadInput').val('');
				    }
			    },				    
			    error : function(xhr, status) {			    	
			    }			    
			});
		}

		//funcion para obtener las sociedades y cargarlas al combobox
		function obtenerSociedades(objetivo)
		{				
		    url = '/index.php/sociedad/listar';
		    
			$(objetivo).empty();			
					
			$('<option>').
			attr({value:""}).
			text('Seleccione').
			prop({disabled: false}).
			appendTo(objetivo);

			var dato="";
		
			$.ajax({
			    url: url,  
			    type: "POST",
			    data: dato,  
			    async:false,
			    success: function(datos){
				    
					for(var i=0;datos.sociedades.length >= i; i++)
					{
						 $('<option>').
						   attr({value:datos.sociedades[i][0]}).
						   text(datos.sociedades[i][1]).
						   appendTo(objetivo);
					}
			    }
			}); 			
		}


		function limpiarControles()
		{
			$('#tipoSociedadSelect').val('');
			$('#valorImpuestoSociedadInput').val('');
		}

	});
	</script>



</body>
</html>
