<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title><?=$this->nombre_sitio?></title>
<!-- Tell the browser to be responsive to screen width -->
<meta
	content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
	name="viewport">
<!-- Bootstrap 3.3.4 -->
<link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet"
	type="text/css" />
<!-- Font Awesome Icons -->
<link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet"
	type="text/css" />
<!-- Ionicons -->
<link href="/ionicons/css/ionicons.min.css" rel="stylesheet"
	type="text/css" />
<!-- DATA TABLES -->
<!-- <link href="/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />-->
<link href="/plugins/datatables/jquery.dataTables.css" rel="stylesheet"
	type="text/css" />
<link href="/plugins/datatables/dataTables.tableTools.css"
	rel="stylesheet">

<link href="/plugins/datatables/dataTables.responsive.css"
	rel="stylesheet" type="text/css" />

<!-- datepicker, estilos calendario -->
<link href="/plugins/datepicker/datepicker3.css" rel="stylesheet"
	type="text/css" />

<!-- iCheck for checkboxes and radio inputs -->
<link href="../../plugins/iCheck/all.css" rel="stylesheet"
	type="text/css" />

<!-- Theme style -->
<link href="/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
<!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
<link href="/dist/css/skins/<?=$this->skin?>.min.css" rel="stylesheet"
	type="text/css" />

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

<style>
.editar {
	width: 20px;
	height: 40px;
	padding: 0px;
	margin: 0px;
}

#formModificaCobro .error {
	color: Crimson
}
</style>
</head>
<!--
  BODY TAG OPTIONS:
  =================
  Apply one or more of the following classes to get the
  desired effect
  |---------------------------------------------------------|
  | SKINS         | skin-blue                               |
  |               | skin-black                              |
  |               | skin-purple                             |
  |               | skin-yellow                             |
  |               | skin-red                                |
  |               | skin-green                              |
  |---------------------------------------------------------|
  |LAYOUT OPTIONS | fixed                                   |
  |               | layout-boxed                            |
  |               | layout-top-nav                          |
  |               | sidebar-collapse                        |
  |               | sidebar-mini                            |
  |---------------------------------------------------------|
  -->
<body class="<?=$this->skin?> sidebar-mini">
	<div class="wrapper">


		<!-- Main Header -->
      	<?=$this->render('head.phtml') ?>	
  <!-- Fin Main Header -->

		<!-- Left side column. contains the logo and sidebar -->
		<aside class="main-sidebar">

			<!-- sidebar: style can be found in sidebar.less -->
			<section class="sidebar">

				<!-- Sidebar user panel (optional) -->
				<?=$this->render('sidebaruserpanel.phtml') ?>	
		  <!-- Fin Sidebar user panel -->

				<!-- Sidebar Menu -->
				<?=$this->render('menu.phtml') ?>		
        </section>
			<!-- /.sidebar -->
		</aside>

		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			<!-- Main content -->
       
          <?=$this->layout()->content?>
       
        <!-- /.content -->
		</div>
		<!-- /.content-wrapper -->

		<!-- Main Footer -->
			
			<?= $this->render('footer.phtml')?>

      <!-- Control Sidebar -->
		<!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
		<div class="control-sidebar-bg"></div>
	</div>
	<!-- ./wrapper -->

	<!-- REQUIRED JS SCRIPTS -->

	<!-- jQuery 2.1.4 -->
	<script src="/plugins/jQuery/jQuery-2.1.4.min.js"
		type="text/javascript"></script>
	<!-- Bootstrap 3.3.2 JS -->
	<script src="/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<!-- DATA TABES SCRIPT -->
	<script src="/plugins/datatables/jquery.dataTables.min.js"
		type="text/javascript"></script>

	<script src="/plugins/datatables/dataTables.responsive.js"
		type="text/javascript"></script>

	<!-- <script src="/plugins/datatables/dataTables.bootstrap.min.js" type="text/javascript"></script>-->
	<!-- SlimScroll -->
	<script src="/plugins/slimScroll/jquery.slimscroll.min.js"
		type="text/javascript"></script>
	<!-- FastClick -->

	<script src="/plugins/datatables/fnReloadAjax.js" cache="false"></script>
	<script src="/plugins/datatables/dataTables.tableTools.js"
		cache="false"></script>

	<script src="/plugins/fastclick/fastclick.min.js"
		type="text/javascript"></script>
	<!-- AdminLTE App -->
	<script src="/dist/js/app.min.js" type="text/javascript"></script>
	<!-- AdminLTE for demo purposes -->
	<script src="/dist/js/demo.js" type="text/javascript"></script>

	<!-- date-picker -->
	<script src="/plugins/datepicker/bootstrap-datepicker.js"
		type="text/javascript"></script>

	<!-- iCheck 1.0.1 Script checkbox y radiobuttons -->
	<script src="../../plugins/iCheck/icheck.min.js" type="text/javascript"></script>

	<script src="/plugins/jquerynumeric/jquery.numeric.js"
		type="text/javascript"></script>

	<!-- Jquery Validate -->

	<script src="/plugins/jqueryvalidate/jquery.validate.min.js"
		type="text/javascript"></script>
	<script src="/plugins/jqueryvalidate/additional-methods.min.js"
		type="text/javascript"></script>
	<script src="/plugins/jqueryvalidate/messages_es.min.js"
		type="text/javascript"></script>

	<!-- JQUERY Number -->
	<script src="/plugins/jquerynumber/jquery.number.js"
		type="text/javascript"></script>

	<script type="text/javascript">
	$(function(){

		var idCobro='<?= $_REQUEST['idCobro'] ?>';
		var tipo='<?= $_REQUEST['tipo'] ?>';
		var dominio='<?=$this->urlaplicacion?>';
		var valorUF=0;

		if(idCobro=='' && tipo=='')
		{
			window.location.href=dominio+"/index.php/rut/buscarporsociedad";
		}		

		obtenerFormasPago('#formaPagoSelectEdit');
		
		obtenerConceptosCobro('#tipoCobroSelectEdit');

		obtenerEjecutivos('#ejecutivoSelectEdit');		

		obtenerDatosDelCobro(idCobro,tipo);

		$('#ingresoMontoMonedaEdit').number( true, 0,',','.' );
		$('#ingresoMontoUfEdit').number( true, 1,',','.');
		
		$("#formModificaCobro").validate({
			debug:true,
			rules:{
				nombreClienteEdit:{
					required:true
				},
				tipoCobroSelectEdit:{
					required: true
				},	
				golsaEdit:{
					required: true
				},
				ingresoMontoUfEdit:{
					required: true
				},	
				ingresoMontoMonedaEdit:{
					required: true
				},	
				ejecutivoSelectEdit:{
					required: true
				},				
				fechaCobroEdit:{
					required: true
				},
				rutEdit:{
					required: true,
				},
				formaPagoSelectEdit:{
					required: true
				},
				ingresoCheckEdit:{
					required: false
				}				
			},
			messages:{
				nombreClienteEdit:"Debe ingresar un nombre.",
				tipoCobroSelectEdit:"Debe seleccionar un elemento de la lista.",		
				golsaEdit:"Debe ingresar una glosa",	
				ingresoMontoMonedaEdit:"Debe ingresar el valor monetario del cobro",	
				ingresoMontoUfEdit:"Debe ingresar el valor en uf",	
				ingresoMontoSelectEdit:"Debe seleccionar un elemento de la lista",
				ejecutivoSelectEdit:"Debe seleccionar un elemento de la lista",
				fechaCobroEdit:"De ingresar la fecha de cobro",
				rutEdit:"Debe ingresar el rut",
				formaPagoSelectEdit:"Debe seleccionar un elemento de la lista",				
			},
			invalidHandler:function(event, validator)
			{
				
			},	
			submitHandler:function(datos)
			{
				url='/index.php/cobroindividual/modificarcobro';			

				var esingreso="2";
				
				if($('.esingreso').hasClass('checked'))
				{
					esingreso="1";
				}
				
	        	var datoCobroModifica="idConceptoCobro="+$('#tipoCobroSelectEdit').val()+
					        		  "&fechaCobro="+$('#fechaCobroEdit').val()+
					        		  "&glosaCobro="+$('#golsaEdit').val()+
					        		  "&montoCobro="+$('#ingresoMontoUfEdit').val()+
					        		  "&pagoCobro="+$('#formaPagoSelectEdit').val()+
					        		  "&observacionCobro="+$('#observacionesEdit').val()+
					        		  "&esingreso="+esingreso+
					        		  "&idCobro="+idCobro+
					        		  "&idUsuario="+$('#ejecutivoSelectEdit').val()+
					        		  "&valorUF="+valorUF+
					        		  "&valorMoneda="+$('#ingresoMontoMonedaEdit').val();
	      		
	        	$.ajax({
	        		url: url,  
	        		type: "POST",
	        		data: datoCobroModifica,
	        		success: function(datos)
	        		{	
	            		if(datos.modifica[0]=='1')	
	            		{
	                		$('#mensajeCorrectoModificacion').removeClass('hide');	

	                		$('#ingresoMontoUfEdit').val();
	                		$('#ingresoMontoMonedaEdit').val();
	                		$('#observacionesEdit').val();    
	                		$('#golsaEdit').val();                		
	            		}
	            		else if(datos.modifica[0]=='2')	
	            		{
	            			$('#mensajeProblemasModificacion').removeClass('hide');	            			
	            		}
	            		else if(datos.modifica[0]=='3')	
		            	{
	            			$('#mensajeProblemasModificacion').removeClass('hide');
	            		}
	    		    },
	    		    error : function(xhr, status) 
				    {					   
	    		    	$('#mensajeProblemasModificacion').removeClass('hide');
	    		    	
				    }	
	   			}); 
			}			
		});	

		$('#fechaCobroEdit').on('changeDate',function()
		{
				fecha=$('#fechaCobroEdit').val().toString().split('-');
				
				url="/index.php/valores/obteneruf";

					data="anioUf="+$.trim(fecha['2'].toString())+"&mesUf="+$.trim(fecha['1'].toString());

					fecha="";

					objetivo='#ufSelect';
					
					$(objetivo).empty();

					$('<option>').
					attr({value:"0"}).
					text('Seleccione').
					prop({disabled: false}).
					appendTo(objetivo);

					$.ajax({
					    url: url,  
					    type: "POST",
					    data: data,  
					    async:false,
					    success: function(datos)
					   	{		 				  
					    	if(datos.valoruf.length>0)
					    	{
								$('<option selected="selected">').
								attr({value:datos.valoruf[1]}).
								text("$ "+datos.valoruf[0]).
								appendTo(objetivo);
								
								$('#buttonCobroIndividual').attr({"disabled":false});

								$('#actualizarUF').addClass('hide');

								valorUF=datos.valoruf[0];	

								$('#ingresoMontoUfEdit').val('');
								$('#ingresoMontoMonedaEdit').val('');

								if($('.esingreso').hasClass('checked'))
								{
									$('#formaPagoSelectEdit').val(6);
								}
								
						    }
						    else
						    {
						    	 $('<option selected="selected">').
								 attr({value:'sinuf'}).
								 text("Sin Uf").
								 appendTo(objetivo);

								 $('#actualizarUF').removeClass('hide');
								   
								 $('#buttonCobroIndividual').attr({"disabled":true});
						    }
				 	    }
					}); 
				});

		$('#buttonActualizarUF').on('click',function(){
			$('#actualizarUF').addClass('hide');
		});

		$('#fechaCobroEdit').datepicker({
			autoclose:true
		});
		
        $('#ingresoCheckEdit').iCheck({
          checkboxClass: 'icheckbox_minimal-blue esingreso',
        });

        $("#ingresoMontoInput").numeric(',');
		

		$('#buttonMensajeCorrectoModificacion').on('click',function()
		{
			$('#mensajeCorrectoModificacion').addClass('hide');
		});

		$('#buttonMensajeProblemasModificacion').on('click',function()
		{
			$('#mensajeProblemasModificacion').addClass('hide');
		});

		//accion para transforma la uf en moneda para el valor de mensualidad
		$('#ingresoMontoUfEdit').on('keyup',function()
		{			
			if($('#ingresoMontoUfEdit').val()!='')
			{
				montoUF=(parseFloat(valorUF)*parseFloat($('#ingresoMontoUfEdit').val())).toFixed(0);

				$('#ingresoMontoMonedaEdit').val(montoUF);

				if($('.esingreso').hasClass('checked'))
				{
					if(parseFloat(montoUF)==0)
					{
						$('#formaPagoSelectEdit').val(6);				
						
					}
					else if(parseFloat(montoUF)>0)
					{
						$('#formaPagoSelectEdit').val(5);					
						
					}					
				}
				else
				{
					if(parseFloat(montoUF)==0)
					{
						$('#formaPagoSelectEdit').val(6);					
						$('#formaPagoSelectEdit').find('option[value="1"],option[value="2"],option[value="3"],option[value="4"],option[value="5"]').attr({"disabled":true});
						$('#formaPagoSelectEdit').find('option[value="6"]').attr({"disabled":false});
					}
					else
					{
						$('#formaPagoSelectEdit').val("");					
						$('#formaPagoSelectEdit').find('option[value="1"],option[value="2"],option[value="3"],option[value="4"],option[value="5"]').attr({"disabled":false});
						$('#formaPagoSelectEdit').find('option[value="6"]').attr({"disabled":true});	
					}
				}
				
			}
			else
			{
				$('#ingresoMontoMonedaEdit').val('');
			}
						
		});

		//accion para transforma el valor monetario de la mensualidad a uf
		$('#ingresoMontoMonedaEdit').on('keyup',function()
		{			
			if($('#ingresoMontoMonedaEdit').val()!='')
			{
				montoMoneda=$(this).val();		
				$('#ingresoMontoUfEdit').val((parseFloat($('#ingresoMontoMonedaEdit').val())/parseFloat(valorUF)).toFixed(2));

				if($('.esingreso').hasClass('checked'))
				{
					if(parseFloat(montoMoneda)==0)
					{
						$('#formaPagoSelectEdit').val(6);					
				
					}
					else if(parseFloat(montoMoneda)>0)
					{
						$('#formaPagoSelectEdit').val(5);				
					}					
				}
				else
				{
					if(parseFloat(montoMoneda)==0)
					{
						$('#formaPagoSelectEdit').val(6);					
						$('#formaPagoSelectEdit').find('option[value="1"],option[value="2"],option[value="3"],option[value="4"],option[value="5"]').attr({"disabled":true});
						$('#formaPagoSelectEdit').find('option[value="6"]').attr({"disabled":false});
					}
					else
					{
						$('#formaPagoSelectEdit').val('');					
						$('#formaPagoSelectEdit').find('option[value="1"],option[value="2"],option[value="3"],option[value="4"],option[value="5"]').attr({"disabled":false});
						$('#formaPagoSelectEdit').find('option[value="6"]').attr({"disabled":true});	
					}
				}
			}
			else
			{
				$('#ingresoMontoUfEdit').val('');
			}
		});
		
        $('#tipoCobroSelectEdit').on('change',function()
        {
        	url='/index.php/concepto/listar';			
        			
        	var dato="";				
        		
        	$.ajax({
        		url: url,  
        		type: "POST",
        		data: dato,
        		success: function(datos)
        		{				
        		 	for(var i=0;datos.data.length >= i; i++)
        			{
        				if($('#tipoCobroSelectEdit').val()==datos.data[i][0])
        				{
        					if(datos.data[i][3]=="si")
        					{
        						$('.esingreso').addClass('checked');
        						$('.esingreso').attr({"aria-checked":true});
        					}
        					else
        					{
        						$('.esingreso').removeClass('checked');
        						$('.esingreso').attr({"aria-checked":false});
        					}
        				}						
        			}	
    		    }
   			}); 
        			
        });
        
		function obtenerDatosDelCobro(idCobros,tipoCobro)
		{
			url = '/index.php/cobroindividual/obtenerdatoscobrobyid';

			var dato="idCobro="+idCobros+"&tipoCobro="+tipoCobro;
		
			$.ajax({
			    url: url,  
			    type: "POST",
			    data: dato,
			    success: function(datos)
			    {		    	
			    	$('#rutEdit').val(datos.obtener[1]);				    
					$('#tipoCobroSelectEdit').val(datos.obtener[2]);
					$('#formaPagoSelectEdit').val(datos.obtener[3]);
					$('#fechaCobroEdit').val(datos.obtener[4]);
					$('#golsaEdit').val(datos.obtener[5]);
					$('#ingresoMontoUfEdit').val(datos.obtener[6]);
					$('#observacionesEdit').val(datos.obtener[7]);
					
					if((parseFloat(datos.obtener[6])==0))
					{						
						$('#formaPagoSelectEdit').find('option[value="1"],option[value="2"],option[value="3"],option[value="4"]').attr({"disabled":true});
					}
					else
					{
						$('#formaPagoSelectEdit').find('option[value="6"]').attr({"disabled":true});
					}
					
					if(datos.obtener[8]=='1')
					{
						$('.esingreso').addClass('checked');
						$('.esingreso').attr({"aria-checked":true});

						//$('#formaPagoSelectEdit').attr({"disabled":true});
						
						obtenerUfAsociadaAlCobro('#ufSelect','',datos.obtener[9]);
						valorUF=parseFloat($.trim(datos.obtener[9].toString().replace('$','')));

						$('#ingresoMontoMonedaEdit').val(datos.obtener[10]);						
					}
					else
					{
						obtenerUfAsociadaAlCobro('#ufSelect','',datos.obtener[8]);
						valorUF=parseFloat($.trim(datos.obtener[8].toString().replace('$','')));		

						$('#ingresoMontoMonedaEdit').val(datos.obtener[9]);					
					}

					

					 obtenerDatosRutCliente(datos.obtener[0]);
					 obtenerDatosClienteByRut(datos.obtener[0]);
			    }
			}); 
		}

		 //obtengo los los datos del rut segun el rut seleccionado
	    function obtenerDatosRutCliente(idRuts)
		{				
		    url = '/index.php/rut/obtenerrubyid';

			var dato="idRut="+idRuts;
		
			$.ajax({
			    url: url,  
			    type: "POST",
			    data: dato,
			    success: function(datos)
			    {					    					
					$('#razonSocialRut').val(datos.rut[3]);	
					$('#rutCliente').val(datos.rut[4]);	
			    }
			}); 			
		}

		function obtenerUfAsociadaAlCobro(objetivo,valor,text)
		{    		    
			$(objetivo).empty();		
			
			$('<option>').
			attr({value:valor}).
			text("$ "+text).
			prop({disabled: false}).
			appendTo(objetivo);    			
		} 

		
		function obtenerDatosClienteByRut(idRuts)
			{				
			    url = '/index.php/cliente/obtenerbyrut';

				var dato="idRut="+idRuts;
			
				$.ajax({
				    url: url,  
				    type: "POST",
				    data: dato,
				    success: function(datos)
				    {					    
						$('#nombreClienteEdit').val(datos.cliente[0]);	
						$('#ejecutivoSelectEdit').val(datos.cliente[1]);	
				    }
				}); 			
			}

		//obtengo los ejecutivos regitrados
		function obtenerEjecutivos(objetivo)
		{				
		    url = '/index.php/usuario/listar';
		    
			$(objetivo).empty();			
					
			$('<option>').
			attr({value:""}).
			text('Seleccione').
			prop({disabled: false}).
			appendTo(objetivo);

			var dato="";
		
			$.ajax({
			    url: url,  
			    type: "POST",
			    data: dato, 
			    async:false,
			    success: function(datos){
				    
			    	 $.each(datos.data, function( index, value ) {
							
						 $('<option>').
						   prop({value:value[0]}).
						   text(value[1]).
						   appendTo(objetivo);
					});	
			    }
			}); 			
		}
			
	 	//obtengo los conceptos de cobro
	    function obtenerConceptosCobro(objetivo)
		{				
		    url = '/index.php/concepto/listar';
		    
			$(objetivo).empty();			
					
			$('<option>').
			attr({value:""}).
			text('Seleccione').
			prop({disabled: false}).
			appendTo(objetivo);

			var dato="";
		
			$.ajax({
			    url: url,  
			    type: "POST",
			    data: dato, 
			    async:false,
			    success: function(datos){
				    
			    	 $.each(datos.data, function( index, value ) {
							
						 $('<option>').
						   prop({value:value[0]}).
						   text(value[1]).
						   appendTo(objetivo);
					});	
			    }
			}); 			
		}


	  //Obtengo formas de pago 
	    function obtenerFormasPago(objetivo)
		{				
		    url = '/index.php/cobroindividual/obtenerformapago';
		    
			$(objetivo).empty();			
					
			$('<option>').
			attr({value:""}).
			text('Seleccione').
			prop({disabled: false}).
			appendTo(objetivo);

			var dato="";
		
			$.ajax({
			    url: url,  
			    type: "POST",
			    data: dato, 
			    success: function(datos){
				    
			    	 $.each(datos.formapago, function( index, value ) {
							
						 $('<option>').
						   prop({value:value[0]}).
						   text(value[1]).
						   appendTo(objetivo);
					});	
			    }
			}); 			
		}


	});
	</script>

</body>
</html>
