<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title><?=$this->nombre_sitio?></title>
<!-- Tell the browser to be responsive to screen width -->
<meta
	content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
	name="viewport">
<!-- Bootstrap 3.3.4 -->
<link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet"
	type="text/css" />
<!-- Font Awesome Icons -->
<link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet"
	type="text/css" />
<!-- Ionicons -->
<link href="/ionicons/css/ionicons.min.css" rel="stylesheet"
	type="text/css" />
<!-- DATA TABLES -->
<!-- <link href="/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />-->
<link href="/plugins/datatables/jquery.dataTables.css" rel="stylesheet"
	type="text/css" />
<link href="/plugins/datatables/dataTables.tableTools.css"
	rel="stylesheet">

<link href="/plugins/datatables/dataTables.responsive.css"
	rel="stylesheet" type="text/css" />

<!-- iCheck for checkboxes and radio inputs -->
<link href="../../plugins/iCheck/all.css" rel="stylesheet"
	type="text/css" />

<!-- datepicker, estilos calendario -->
<link href="/plugins/datepicker/datepicker3.css" rel="stylesheet"
	type="text/css" />
<!-- Theme style -->
<link href="/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
<!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
<link href="/dist/css/skins/<?=$this->skin?>.min.css" rel="stylesheet"
	type="text/css" />

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

<style>
.editar {
	width: 20px;
	height: 40px;
	padding: 0px;
	margin: 0px;
}

#formIngresoContacto .error {
	color: Crimson
}
</style>

</head>
<!--
  BODY TAG OPTIONS:
  =================
  Apply one or more of the following classes to get the
  desired effect
  |---------------------------------------------------------|
  | SKINS         | skin-blue                               |
  |               | skin-black                              |
  |               | skin-purple                             |
  |               | skin-yellow                             |
  |               | skin-red                                |
  |               | skin-green                              |
  |---------------------------------------------------------|
  |LAYOUT OPTIONS | fixed                                   |
  |               | layout-boxed                            |
  |               | layout-top-nav                          |
  |               | sidebar-collapse                        |
  |               | sidebar-mini                            |
  |---------------------------------------------------------|
  -->
<body class="<?=$this->skin?> sidebar-mini">
	<div class="wrapper">


		<!-- Main Header -->
      	<?=$this->render('head.phtml') ?>	
  <!-- Fin Main Header -->

		<!-- Left side column. contains the logo and sidebar -->
		<aside class="main-sidebar">

			<!-- sidebar: style can be found in sidebar.less -->
			<section class="sidebar">

				<!-- Sidebar user panel (optional) -->
				<?=$this->render('sidebaruserpanel.phtml') ?>	
		  <!-- Fin Sidebar user panel -->

				<!-- Sidebar Menu -->
				<?=$this->render('menu.phtml') ?>		
        </section>
			<!-- /.sidebar -->
		</aside>

		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			<!-- Main content -->
       
          <?=$this->layout()->content?>
       
        <!-- /.content -->
		</div>
		<!-- /.content-wrapper -->

		<!-- Main Footer -->
			
			<?= $this->render('footer.phtml')?>

      <!-- Control Sidebar -->
		<!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
		<div class="control-sidebar-bg"></div>
	</div>
	<!-- ./wrapper -->

	<!-- REQUIRED JS SCRIPTS -->

	<!-- jQuery 2.1.4 -->
	<script src="/plugins/jQuery/jQuery-2.1.4.min.js"
		type="text/javascript"></script>

	<!-- Bootstrap 3.3.2 JS -->
	<script src="/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

	<!-- DATA TABES SCRIPT -->
	<script src="/plugins/datatables/jquery.dataTables.min.js"
		type="text/javascript"></script>
	<script src="/plugins/datatables/dataTables.responsive.js"
		type="text/javascript"></script>

	<!-- <script src="/plugins/datatables/dataTables.bootstrap.min.js" type="text/javascript"></script>-->

	<!-- SlimScroll -->
	<script src="/plugins/slimScroll/jquery.slimscroll.min.js"
		type="text/javascript"></script>

	<!-- FastClick -->
	<script src="/plugins/datatables/fnReloadAjax.js" cache="false"></script>
	<script src="/plugins/datatables/dataTables.tableTools.js"
		cache="false"></script>

	<script src="/plugins/fastclick/fastclick.min.js"
		type="text/javascript"></script>

	<!-- AdminLTE App -->
	<script src="/dist/js/app.min.js" type="text/javascript"></script>

	<!-- AdminLTE for demo purposes -->
	<script src="/dist/js/demo.js" type="text/javascript"></script>

	<!-- iCheck 1.0.1 Script checkbox y radiobuttons -->
	<script src="../../plugins/iCheck/icheck.min.js" type="text/javascript"></script>

	<!-- date-picker -->
	<script src="/plugins/datepicker/bootstrap-datepicker.js"
		type="text/javascript"></script>

	<!-- Jquery Validate -->

	<script src="/plugins/jqueryvalidate/jquery.validate.min.js"
		type="text/javascript"></script>
	<script src="/plugins/jqueryvalidate/additional-methods.min.js"
		type="text/javascript"></script>
	<script src="/plugins/jqueryvalidate/messages_es.min.js"
		type="text/javascript"></script>

	<script type="text/javascript">

	$(function(){	

		var idCliente="<?php echo $_REQUEST['idCliente'] ?>";

		if(idCliente=="")
		{
			window.location.href=dominio+"index.php/cliente/buscarpornombre";
		}

		//valido formulario ingreso de cliente
		$("#formIngresoContacto").validate({
			debug:true,
			rules:{
				nombreClienteInput:{
					required:true
				},
				emailClienteInput:{
					required: true
				},
				telefonoClienteInput:{
					required:true
				},
				celularClienteInput:{
					required:true
				},
				listadoRutCliente:{
					required:true
				}				
			},
			messages:{
				nombreClienteInput:"Debe ingresar el nombre",
				emailClienteInput:"Debe ingresar el email",
				telefonoClienteInput:"Debe ingresar en n&uacute;mero de tel&eacute;fono",
				celularClienteInput:"Debe ingresar el celular del cliente",
				listadoRutCliente:"Seleccione al rut que desea asignar el contacto"
				
			},
			invalidHandler:function(event, validator){
				
			},	
			submitHandler:function(datos){

				//direccion del controler.
				url="/index.php/contacto/ingreso";	

				var cobro='2';		
				var boleteo='2';	

				if($('.cobro').hasClass('checked'))
				{
					cobro='1';	
				}	

				if($('.boleteo').hasClass('checked'))
				{
					boleteo='1';	
				}	

				//obtengo los datos del formulario validado
				var datosContacto = "nombreContacto="+$('#nombreClienteInput').val().toUpperCase()+
									"&emailContacto="+$('#emailClienteInput').val()+
									"&telefonoContacto="+$('#telefonoClienteInput').val()+
									"&celularContacto="+$('#celularClienteInput').val()+
									"&cobro="+cobro+
									"&boleteo="+boleteo+
									"&idCliente="+idCliente;                                         
				
				//ajax para enviar los datos al controler que registra.
				$.ajax({
				    url : url,					    
				    type: "POST",					   
				    data : datosContacto,
				    success: function(datos)
				    {							
				    	if(datos.registro[0]=='1')
						{								
							$('#mensajeCorrectoRegistro').removeClass('hide');
							limpiaControles();
						}
				    	else if(datos.registro[0]=='2')
				    	{					    		
				    		$('#mensajeProblemasRegistro').removeClass('hide');
				    		limpiaControles();
				    	}
				    	else if(datos.registro[0]=='3')
				    	{
					    	$('#mensajeEmailEncontrado').removeClass('hide');
					    	$('#emailClienteInput').val();
				    	}				    	
				    },				    
				    error : function(xhr, status) 
				    {
				    	$('#mensajeProblemasRegistro').removeClass('hide');
				    	limpiaControles();
				    }			    
				});				
				
			}			
		});

		function limpiaControles()
		{
			$('.form-control').val('');
			$('.cobro').removeClass('checked');
		  	$('.cobro').attr({"aria-checked":false});
		  	$('.boleteo').removeClass('checked');
		  	$('.boleteo').attr({"aria-checked":false});
		} 

		

		$('#buttonMensajeEmailEncontrado').on('click',function()
		{
			$('#mensajeEmailEncontrado').addClass('hide');
		});

		$('#buttonMensajeNombreEncontrado').on('click',function()
		{
			$('#mensajeNombreEncontrado').addClass('hide');
		});

		$('#buttonMensajeCorrectoRegistro').on('click',function()
		{
			$('#mensajeCorrectoRegistro').addClass('hide');
		});

		$('#buttonMensajeProblemasRegistro').on('click',function()
		{
			$('#mensajeProblemasRegistro').addClass('hide');
		});

		$('#boleteoCheck').iCheck({
	        checkboxClass: 'icheckbox_minimal-blue boleteo',
	    });

		$('#cobroCheck').iCheck({
	         checkboxClass: 'icheckbox_minimal-blue cobro',
	    });
		
		

	});
	
	</script>

</body>
</html>
