<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title><?=$this->nombre_sitio?></title>
<!-- Tell the browser to be responsive to screen width -->
<meta
	content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
	name="viewport">
<!-- Bootstrap 3.3.4 -->
<link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet"
	type="text/css" />
<!-- Font Awesome Icons -->
<link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet"
	type="text/css" />

<!-- daterange picker, estilos calendario -->
<link href="/plugins/daterangepicker/daterangepicker-bs3.css"
	rel="stylesheet" type="text/css" />
<link href="/plugins/datepicker/datepicker3.css" rel="stylesheet"
	type="text/css" />

<!-- Ionicons -->
<link href="/ionicons/css/ionicons.min.css" rel="stylesheet"
	type="text/css" />
<!-- DATA TABLES -->
<!-- <link href="/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />-->
<link href="/plugins/datatables/jquery.dataTables.css" rel="stylesheet"
	type="text/css" />
<link href="/plugins/datatables/dataTables.tableTools.css"
	rel="stylesheet">

<link href="/plugins/datatables/dataTables.responsive.css"
	rel="stylesheet" type="text/css" />

<!-- iCheck for checkboxes and radio inputs -->
<link href="../../plugins/iCheck/all.css" rel="stylesheet"
	type="text/css" />

<!-- Theme style -->
<link href="/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
<!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
<link href="/dist/css/skins/<?=$this->skin?>.min.css" rel="stylesheet"
	type="text/css" />
<link href="/plugins/JqueryAlerts/jquery.alerts.css" rel="stylesheet">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

<style>
.editar {
	width: 20px;
	height: 40px;
	padding: 0px;
	margin: 0px;
}

.right {
	align: right;
}

.marginBottomButton {
	margin-bottom: 3px;
}

#formNuevoProveedor .error {
	color: Crimson
}
</style>
</head>
<!--
  BODY TAG OPTIONS:
  =================
  Apply one or more of the following classes to get the
  desired effect
  |---------------------------------------------------------|
  | SKINS         | skin-blue                               |
  |               | skin-black                              |
  |               | skin-purple                             |
  |               | skin-yellow                             |
  |               | skin-red                                |
  |               | skin-green                              |
  |---------------------------------------------------------|
  |LAYOUT OPTIONS | fixed                                   |
  |               | layout-boxed                            |
  |               | layout-top-nav                          |
  |               | sidebar-collapse                        |
  |               | sidebar-mini                            |
  |---------------------------------------------------------|
  -->
<body class="<?=$this->skin?> sidebar-mini">
	<div class="wrapper">


		<!-- Main Header -->
      	<?=$this->render('head.phtml') ?>	
  <!-- Fin Main Header -->

		<!-- Left side column. contains the logo and sidebar -->
		<aside class="main-sidebar">

			<!-- sidebar: style can be found in sidebar.less -->
			<section class="sidebar">

				<!-- Sidebar user panel (optional) -->
				<?=$this->render('sidebaruserpanel.phtml') ?>	
		  <!-- Fin Sidebar user panel -->

				<!-- Sidebar Menu -->
				<?=$this->render('menu.phtml') ?>		
        </section>
			<!-- /.sidebar -->
		</aside>

		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			<!-- Main content -->
       
          <?=$this->layout()->content?>
       
        <!-- /.content -->
		</div>
		<!-- /.content-wrapper -->

		<!-- Main Footer -->
			
			<?= $this->render('footer.phtml')?>

      <!-- Control Sidebar -->
		<!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
		<div class="control-sidebar-bg"></div>
	</div>
	<!-- ./wrapper -->

	<!-- REQUIRED JS SCRIPTS -->

	<!-- jQuery 2.1.4 -->
	<script src="/plugins/jQuery/jQuery-2.1.4.min.js"
		type="text/javascript"></script>

	<!-- Script RUT -->
	<script src="/plugins/jQueryRut/jquery.Rut.js" type="text/javascript"></script>

	<!-- Bootstrap 3.3.2 JS -->
	<script src="/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<!-- DATA TABES SCRIPT -->
	<script src="/plugins/datatables/jquery.dataTables.min.js"
		type="text/javascript"></script>

	<script src="/plugins/datatables/dataTables.responsive.js"
		type="text/javascript"></script>

	<!-- <script src="/plugins/datatables/dataTables.bootstrap.min.js" type="text/javascript"></script>-->
	<!-- SlimScroll -->
	<script src="/plugins/slimScroll/jquery.slimscroll.min.js"
		type="text/javascript"></script>
	<!-- FastClick -->

	<script src="/plugins/datatables/fnReloadAjax.js" cache="false"></script>
	<script src="/plugins/datatables/dataTables.tableTools.js"
		cache="false"></script>

	<script src="/plugins/fastclick/fastclick.min.js"
		type="text/javascript"></script>
	<!-- AdminLTE App -->
	<script src="/dist/js/app.min.js" type="text/javascript"></script>
	<!-- AdminLTE for demo purposes -->
	<script src="/dist/js/demo.js" type="text/javascript"></script>

	<!-- Jquery Validate -->
	<script src="/plugins/jqueryvalidate/jquery.validate.min.js"
		type="text/javascript"></script>
	<script src="/plugins/jqueryvalidate/additional-methods.min.js"
		type="text/javascript"></script>
	<script src="/plugins/jqueryvalidate/messages_es.min.js"
		type="text/javascript"></script>
		<script src="/plugins/jQuery/jquery-migrate-1.2.1.js"
		type="text/javascript"></script>	
	<script src="/plugins/JqueryAlerts/jquery.alerts.js"
		type="text/javascript"></script>
		

	
	<script type="text/javascript">
		$(function(){

			var idProveedor="";

			var tablaProveedores = $('#tableMantenedorProveedores').dataTable( {
		        dom: 'T<"clear">lfrtip',
		        bFilter: false,
		        "responsive":true,
		        "bLengthChange": false,
		        "autoWidth": false,	      
		        tableTools: {
		            "sSwfPath": "/swf/copy_csv_xls_pdf.swf",
		            "sRowSelect": "single",
		            "aButtons": [ ]
		        },
		        "language": {
					"lengthMenu": "Desplegando _MENU_ registros por p&aacute;gina",
					"zeroRecords": "Nada encontrado - Lo sentimos",
					"info": "Mostrando p&aacute;gina _PAGE_ de _PAGES_",
					"infoEmpty": "No hay registros disponibles",
					"infoPostFix":    "",
					"thousands":      ",",
					"loadingRecords": "Cargando...",
					"processing":     "Procesando...",
					"search":         "Buscar:",
					"infoFiltered ": "(Filtrando de un total de _MAX_ registros)",
					"paginate": {
						"first":      "Primero",
						"last":       "&Uacute;ltimo",
						"next":       "Siguiente",
						"previous":   "Anterior"
						}
					}		
		        
		    } );

			listadoConceptos(tablaProveedores);

			//valido el registro del nuevo proveedor.
			$('#formNuevoProveedor').validate({
				debug:true,
				rules:{
					nombreProveedorInput:{
						required:true
					}
				},
				messages:{
					nombreProveedorInput:"Debe ingresar el nombre del nuevo Proveedor"					
				},
				invalidHandler:function(event, validator){
					
				},	
				submitHandler:function(form){	

					//direccion del controler.
					url="/index.php/proveedor/ingresar";

					var datosProveedor = "nombreProveedor="+$('#nombreProveedorInput').val().toLowerCase();                                               
					
					//ajax para enviar los datos al controler que registra.
					$.ajax({
					    url : url,					    
					    type: "POST",					   
					    data : datosProveedor,
					    success: function(datos)
					    {							
					    	if(datos.registro[0]=='1')
							{								
								//registro correcto 
								$('.form-control').val('');											    		
								//$('#mensajeCorrectoRegistro').removeClass('hide');
								jAlert("El proveedor se guard\u00F3 correctamente","Alerta");
								 listadoConceptos(tablaProveedores);
							}
					    	else if(datos.registro[0]=='2')
					    	{					    		
					    		//no registró
					    		$('#mensajeProblemasRegistro').removeClass('hide'); 
					    		$('.form-control').val('');						    	
					    	}
					    	else if(datos.registro[0]=='3')
					    	{
						    	//nombre concepto repetido					    		
					    		$('#mensajeRegistroNombreIgual').removeClass('hide'); 
					    		$('#nombreConceptoInput').val('');
						    		
					    	}
					    },				    
					    error : function(xhr, status) {
					    	$('#mensajeProblemasRegistro').removeClass('hide'); 
				    		$('.form-control').val('');	
					    }			    
					});							
				}	
			});

			//lenato el modal con la información del proveedor a modificar.
			$('#buttonEditaProveedor').on('click',function()
			{
				if($('#tableMantenedorProveedores tbody tr').hasClass('selected'))
				{
					idProveedor=obtenerIdProveedor();
					$('#modalEditarProveedor').modal();					
					$('#nombreProveedorEdit').val(obtenerNombreProveedor().toLowerCase());
				}
				else
				{
					$('#seleccionaConceptoLista').removeClass('hide');
				}
				
			});

			//valido el registro de la actualizacion del proveedor.
			$('#formActualizaProveedor').validate({
				debug:true,
				rules:{
					nombreProveedorEdit:{
						required:true
					}
				},
				messages:{
					nombreProveedorEdit:"Debe ingresar el nombre del nuevo Proveedor"					
				},
				invalidHandler:function(event, validator){
					
				},	
				submitHandler:function(form){	

					//direccion del controler.
					url="/index.php/proveedor/modificar";

					var datosProveedorEdit = "nombreProveedorEdit="+$('#nombreProveedorEdit').val().toLowerCase()+"&idProveedor="+idProveedor;                                               
					
					//ajax para enviar los datos al controler que registra.
					$.ajax({
					    url : url,					    
					    type: "POST",					   
					    data : datosProveedorEdit,
					    success: function(datos)
					    {							
					    	if(datos.edicion[0]=='1')
							{								
								//modificacion correcta 
								$('.form-control').val('');											    		
								$('#conceptoActualizado').removeClass('hide');	
								$('#modalEditarProveedor').modal('hide');							
								listadoConceptos(tablaProveedores);
							}
					    	else if(datos.edicion[0]=='2')
					    	{					    		
					    		//no modificó
					    		$('#mensajeProblemaAccion').removeClass('hide'); 
					    		$('.form-control').val('');						    	
					    	}
					    	
					    },				    
					    error : function(xhr, status) {
					    	$('#mensajeProblemaAccion').removeClass('hide'); 
				    		$('.form-control').val('');	
					    }			    
					});							
				}	
			});
			
			//levanto modal de confirmacion de eliminacion de proveedor
			$('#buttonEliminarProveedor').on('click',function()
			{
				if($('#tableMantenedorProveedores tbody tr').hasClass('selected'))
				{
					idProveedor=obtenerIdProveedor();
					$('#modalEliminarProveedor').modal();		
				}
				else
				{
					$('#seleccionaConceptoLista').removeClass('hide');
				}
				
			});

			//confirmo la accion de eliminar al proveedor.
			$('#buttonEliminaProveedorOk').on('click',function()
			{
				url="/index.php/proveedor/eliminar";					
				var idProv = "idProveedor="+idProveedor;                                               
			
				$.ajax({
				    url : url,					    
				    type: "POST",					   
				    data : idProv,
				    success: function(datos)
				    {		  
						if(datos.eliminar[0]=='1')
						{							
							//$('#conceptoEliminado').removeClass('hide');
							 jAlert("Proveedor eliminado correctamente","Exito");							
							 listadoConceptos(tablaProveedores);
						}
						else if(datos.eliminar[0]=='2')
						{
							$('#mensajeProblemaAccion').removeClass('hide');							
						}								
				    },				    
				    error : function(xhr, status) {
				    	$('#mensajeProblemaAccion').removeClass('hide');		
				    }			    
				});
			});	

			$('#buttonCierraMsgActualizado').on('click',function()
			{
				$('#conceptoActualizado').addClass('hide');
			});
			
			$('#buttonMensajeProblemaAccion').on('click',function()
			{
				$('#mensajeProblemaAccion').addClass('hide');
			});
			
			$('#buttonCierraMsgEliminado').on('click',function()
			{
				$('#conceptoEliminado').addClass('hide');
			});	
			
			$('#buttonCierraMsgSeleccion').on('click',function()
			{
				$('#seleccionaConceptoLista').addClass('hide');
			});

			$('#buttonMensajeCorrectoRegistro').on('click',function(){
				$('#mensajeCorrectoRegistro').addClass('hide');
			});

			$('#buttonMensajeProblemasRegistro').on('click',function(){
				$('#mensajeProblemasRegistro').addClass('hide');
			});

			$('#buttonMensajeRegistroNombreIgual').on('click',function(){
				$('#mensajeRegistroNombreIgual').addClass('hide');
			});

			//obtengo el id del proveedor que será editado o eliminado
			function obtenerIdProveedor()
			{
				var id="";			
					$('#tableMantenedorProveedores').find('tr.selected').each(function(){
						id=$(this).find('td:first').html();				
					});
				return id;
			}

			function obtenerNombreProveedor()
			{
				var nombre="";			
					$('#tableMantenedorProveedores').find('tr.selected').each(function(){
						id=$(this).find('td:first').next('td').html();				
					});
				return id;
			}

			//obtengo el listado de proveedores
			function listadoConceptos(table)
		    {
				url="/index.php/proveedor/listar";
				table.fnClearTable();				
				table.fnReloadAjax(url);			
			}
			
		});

	</script>
	
</body>
</html>
