<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title><?=$this->nombre_sitio?></title>
<!-- Tell the browser to be responsive to screen width -->
<meta
	content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
	name="viewport">
<!-- Bootstrap 3.3.4 -->
<link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet"
	type="text/css" />
<!-- Font Awesome Icons -->
<link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet"
	type="text/css" />

<!-- daterange picker, estilos calendario -->
<link href="/plugins/daterangepicker/daterangepicker-bs3.css"
	rel="stylesheet" type="text/css" />
<link href="/plugins/datepicker/datepicker3.css" rel="stylesheet"
	type="text/css" />

<!-- Ionicons -->
<link href="/ionicons/css/ionicons.min.css" rel="stylesheet"
	type="text/css" />
<!-- DATA TABLES -->
<!-- <link href="/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />-->
<link href="/plugins/datatables/jquery.dataTables.css" rel="stylesheet"
	type="text/css" />
<link href="/plugins/datatables/dataTables.tableTools.css"
	rel="stylesheet">

<link href="/plugins/datatables/dataTables.responsive.css"
	rel="stylesheet" type="text/css" />

<!-- iCheck for checkboxes and radio inputs -->
<link href="../../plugins/iCheck/all.css" rel="stylesheet"
	type="text/css" />

<!-- Theme style -->
<link href="/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
<!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
<link href="/dist/css/skins/<?=$this->skin?>.min.css" rel="stylesheet"
	type="text/css" />

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

<style>
.editar {
	width: 20px;
	height: 40px;
	padding: 0px;
	margin: 0px;
}

.right {
	align: right;
}

.marginBottomButton {
	margin-bottom: 3px;
}

#formNuevoConcepto .error {
	color: Crimson
}
</style>
</head>
<!--
  BODY TAG OPTIONS:
  =================
  Apply one or more of the following classes to get the
  desired effect
  |---------------------------------------------------------|
  | SKINS         | skin-blue                               |
  |               | skin-black                              |
  |               | skin-purple                             |
  |               | skin-yellow                             |
  |               | skin-red                                |
  |               | skin-green                              |
  |---------------------------------------------------------|
  |LAYOUT OPTIONS | fixed                                   |
  |               | layout-boxed                            |
  |               | layout-top-nav                          |
  |               | sidebar-collapse                        |
  |               | sidebar-mini                            |
  |---------------------------------------------------------|
  -->
<body class="<?=$this->skin?> sidebar-mini">
	<div class="wrapper">


		<!-- Main Header -->
      	<?=$this->render('head.phtml') ?>	
  <!-- Fin Main Header -->

		<!-- Left side column. contains the logo and sidebar -->
		<aside class="main-sidebar">

			<!-- sidebar: style can be found in sidebar.less -->
			<section class="sidebar">

				<!-- Sidebar user panel (optional) -->
				<?=$this->render('sidebaruserpanel.phtml') ?>	
		  <!-- Fin Sidebar user panel -->

				<!-- Sidebar Menu -->
				<?=$this->render('menu.phtml') ?>		
        </section>
			<!-- /.sidebar -->
		</aside>

		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			<!-- Main content -->
       
          <?=$this->layout()->content?>
       
        <!-- /.content -->
		</div>
		<!-- /.content-wrapper -->

		<!-- Main Footer -->
			
			<?= $this->render('footer.phtml')?>

      <!-- Control Sidebar -->
		<!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
		<div class="control-sidebar-bg"></div>
	</div>
	<!-- ./wrapper -->

	<!-- REQUIRED JS SCRIPTS -->

	<!-- jQuery 2.1.4 -->
	<script src="/plugins/jQuery/jQuery-2.1.4.min.js"
		type="text/javascript"></script>

	<!-- Script RUT -->
	<script src="/plugins/jQueryRut/jquery.Rut.js" type="text/javascript"></script>

	<!-- Bootstrap 3.3.2 JS -->
	<script src="/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<!-- DATA TABES SCRIPT -->
	<script src="/plugins/datatables/jquery.dataTables.min.js"
		type="text/javascript"></script>

	<script src="/plugins/datatables/dataTables.responsive.js"
		type="text/javascript"></script>

	<!-- <script src="/plugins/datatables/dataTables.bootstrap.min.js" type="text/javascript"></script>-->
	<!-- SlimScroll -->
	<script src="/plugins/slimScroll/jquery.slimscroll.min.js"
		type="text/javascript"></script>
	<!-- FastClick -->

	<script src="/plugins/datatables/fnReloadAjax.js" cache="false"></script>
	<script src="/plugins/datatables/dataTables.tableTools.js"
		cache="false"></script>

	<script src="/plugins/fastclick/fastclick.min.js"
		type="text/javascript"></script>
	<!-- AdminLTE App -->
	<script src="/dist/js/app.min.js" type="text/javascript"></script>
	<!-- AdminLTE for demo purposes -->
	<script src="/dist/js/demo.js" type="text/javascript"></script>

	<!-- iCheck 1.0.1 Script checkbox y radiobuttons -->
	<script src="../../plugins/iCheck/icheck.min.js" type="text/javascript"></script>
	<!-- Jquery Validate -->
	<script src="/plugins/jqueryvalidate/jquery.validate.min.js"
		type="text/javascript"></script>
	<script src="/plugins/jqueryvalidate/additional-methods.min.js"
		type="text/javascript"></script>
	<script src="/plugins/jqueryvalidate/messages_es.min.js"
		type="text/javascript"></script>

	<!-- page script -->

	<script type="text/javascript">
		$(function(){

			var idConcepto="";

			var tableListadoConceptos=$('#tableMantenedorConceptoCobro').dataTable( {
		        dom: 'T<"clear">lfrtip',
		        bFilter: false,
		        "responsive":true,
		        "bLengthChange": false,
		        "autoWidth": false,	      
		        tableTools: {
		            "sSwfPath": "/swf/copy_csv_xls_pdf.swf",
		            "sRowSelect": "single",
		            "aButtons": [ ]
		        },
		        "language": {
					"lengthMenu": "Desplegando _MENU_ registros por p&aacute;gina",
					"zeroRecords": "Nada encontrado - Lo sentimos",
					"info": "Mostrando p&aacute;gina _PAGE_ de _PAGES_",
					"infoEmpty": "No hay registros disponibles",
					"infoPostFix":    "",
					"thousands":      ",",
					"loadingRecords": "Cargando...",
					"processing":     "Procesando...",
					"search":         "Buscar:",
					"infoFiltered ": "(Filtrando de un total de _MAX_ registros)",
					"paginate": {
						"first":      "Primero",
						"last":       "&Uacute;ltimo",
						"next":       "Siguiente",
						"previous":   "Anterior"
						}
					}		
		        
		    } );

			listadoConceptos(tableListadoConceptos);    

			//valido formulario de ingreso de datos	
			$('#formNuevoConcepto').validate({
				debug:true,
				rules:{
					nombreConceptoInput:{
						required:true
					}
				},
				messages:{
					nombreConceptoInput:"Debe ingresar el nombre del concepto"					
				},
				invalidHandler:function(event, validator){
					
				},	
				submitHandler:function(form){	

					//direccion del controler.
					url="/index.php/concepto/ingresar";
							
					var checkAgrupable='2';
					var checkIngreso='2';

					if($('.agrupable').hasClass('checked'))
					{
						checkAgrupable='1';
					}	

					if($('.ingreso').hasClass('checked'))
					{
						checkIngreso='1';
					}			

					//obtengo los datos del formulario validado
					var datosConcepto = "nombreConcepto="+$('#nombreConceptoInput').val().toLowerCase()+"&agrupable="+checkAgrupable+"&ingreso="+checkIngreso;                                               
					
					//ajax para enviar los datos al controler que registra.
					$.ajax({
					    url : url,					    
					    type: "POST",					   
					    data : datosConcepto,
					    success: function(datos)
					    {							
					    	if(datos.registro[0]=='1')
							{								
								//registro correcto 
								$('.form-control').val('');	
								$('.icheckbox_minimal-blue').removeClass('checked');			    		
								$('#mensajeCorrectoRegistro').removeClass('hide');								
								listadoConceptos(tableListadoConceptos);  	
							}
					    	else if(datos.registro[0]=='2')
					    	{					    		
					    		//no registró
					    		$('#mensajeProblemasRegistro').removeClass('hide'); 
					    		$('.form-control').val('');						    	
					    	}
					    	else if(datos.registro[0]=='3')
					    	{
						    	//nombre concepto repetido					    		
					    		$('#mensajeRegistroNombreIgual').removeClass('hide'); 
					    		$('#nombreConceptoInput').val('');
						    		
					    	}
					    },				    
					    error : function(xhr, status) {
					    	$('#mensajeProblemasRegistro').removeClass('hide'); 
				    		$('.form-control').val('');	
					    }			    
					});
							
				}	
			});

			//valido formulario de edición de datos (modal editar)
			$('#formConceptoEditar').validate({
				debug:true,
				rules:{
					nombreConcptoEdit:{
						required:true
					}
				},
				messages:{
					nombreConceptoInput:"Debe ingresar el nombre del concepto"					
				},
				invalidHandler:function(event, validator){
					
				},	
				submitHandler:function(form)
				{					
					//direccion del controler.
					url="/index.php/concepto/modificar";
							
					var checkAgrupableEdit='2';
					var checkIngresoEdit='2';

					if($('.agrupableEdit').hasClass('checked'))
					{
						checkAgrupableEdit='1';
					}	

					if($('.ingresoEdit').hasClass('checked'))
					{
						checkIngresoEdit='1';
					}			

					//obtengo los datos del formulario validado
					var datosConcepto = "nombreConcptoEdit="+$('#nombreConcptoEdit').val()+"&agrupableEdit="+checkAgrupableEdit+"&ingresoEdit="+checkIngresoEdit+"&idConcept="+idConcepto;                                               

					//ajax para enviar los datos al controler que registra.
					$.ajax({
					    url : url,					    
					    type: "POST",					   
					    data : datosConcepto,
					    success: function(datos)
					    {							
					    	if(datos.edicion[0]=='1')
							{								
								//edición correcto 
								$('.form-control').val('');	
								$('.icheckbox_minimal-blue').removeClass('checked');
											    		
								$('#conceptoActualizado').removeClass('hide');
								$('#modalEditarConceptoCobro').modal('hide');								

								listadoConceptos(tableListadoConceptos);
							}
					    	else if(datos.edicion[0]=='2')
					    	{					    		
					    		//no editó
					    		$('#mensajeProblemaAccion').removeClass('hide'); 
					    		$('.form-control').val('');						    	
					    	}
					    },				    
					    error : function(xhr, status) {
					    	$('#mensajeProblemaAccion').removeClass('hide'); 
				    		$('.form-control').val('');	
					    }			    
					});
							
				}	
			});			

			$('#buttonEditaConcepto').on('click',function(){

				if($('#tableMantenedorConceptoCobro tbody tr').hasClass('selected'))
				{
					idConcepto	= obtenerIdConcepto();
					
					if(parseInt(idConcepto)>3)
					{
						$('#modalEditarConceptoCobro').modal();						

						url="/index.php/concepto/obtener";					
						
						var idConcept = "idConcept="+idConcepto;    
						
						$.ajax({
						    url : url,					    
						    type: "POST",					   
						    data : idConcept,
						    success: function(datos)
						    {							    	   		
								$('#nombreConcptoEdit').val(datos.concepto[0]); 

								if(datos.concepto[1]=='1')
								{
									$('.agrupableEdit').addClass('checked');
								}
								else
								{
									$('.agrupableEdit').removeClass('checked');
								}

								if(datos.concepto[2]=='1')
								{
									$('.ingresoEdit').addClass('checked');
								}
								else
								{
									$('.ingresoEdit').removeClass('checked');
								}							
															
						    },				    
						    error : function(xhr, status) 
						    {
						    	
						    }			    
						});
					}
					else
					{
						$('#mensajeConceptoNoMantenible').removeClass('hide');
					}		
				}
				else
				{
					$('#seleccionaConceptoLista').removeClass('hide');
				}			
				
			});

			$('#buttonEliminarConcepto').on('click',function(){

				if($('#tableMantenedorConceptoCobro tbody tr').hasClass('selected'))
				{
					idConcepto	= obtenerIdConcepto();
					
					if(parseInt(idConcepto)>3)
					{
						$('#modalEliminaronceptoCobro').modal();	
					}
					else
					{
						$('#mensajeConceptoNoMantenible').removeClass('hide');
					}									
				}	
				else
				{
					$('#seleccionaConceptoLista').removeClass('hide');
				}			
				
			});

			$('#buttonMensajeConceptoNoMantenible').on('click',function()
			{
				$('#mensajeConceptoNoMantenible').addClass('hide');
			});

			$('#buttonEliminaCocept').on('click',function()
			{
				url="/index.php/concepto/eliminar";					
				var idConcept = "idConcepto="+idConcepto;                                               
			
				$.ajax({
				    url : url,					    
				    type: "POST",					   
				    data : idConcept,
				    success: function(datos)
				    {		  
						if(datos.eliminar[0]=='1')
						{
							listadoConceptos(tableListadoConceptos);   
							$('#conceptoEliminado').removeClass('hide');
						}
						else if(datos.eliminar[0]=='2')
						{
							$('#mensajeProblemaAccion').removeClass('hide');							
						}		
						
				    },				    
				    error : function(xhr, status) {
				    	$('#mensajeProblemaAccion').removeClass('hide');		
				    }			    
				});
			});

			$('#buttonMensajeRegistroNombreIgual').on('click',function()
			{
				$('#mensajeRegistroNombreIgual').addClass('hide');
			});

			$('#buttonCierraMsgActualizado').on('click',function()
			{
				$('#conceptoActualizado').addClass('hide');
			});
			
			$('#buttonMensajeProblemaAccion').on('click',function()
			{
				$('#conceptoEliminado').addClass('hide');
			});

			$('#buttonCierraMsgEliminado').on('click',function()
			{
				$('#conceptoEliminado').addClass('hide');
			});

			$('#buttonCierraMsgSeleccion').on('click',function()
			{
				$('#seleccionaConceptoLista').addClass('hide');
			});

			$('#buttonMensajeCorrectoRegistro').on('click',function()
			{
				$('#mensajeCorrectoRegistro').addClass('hide');
			});

			$('#buttonMensajeProblemasRegistro').on('click',function()
			{
				$('#mensajeProblemasRegistro').addClass('hide');
			});
			
			$('#checkAgrupable').iCheck({
		          checkboxClass: 'icheckbox_minimal-blue agrupable',
		    });

			$('#checkIngreso').iCheck({
		          checkboxClass: 'icheckbox_minimal-blue ingreso',
		    });

			$('#checkAgrupableEdit').iCheck({
		          checkboxClass: 'icheckbox_minimal-blue agrupableEdit',
		    });

			$('#checkIngresoEdit').iCheck({
		          checkboxClass: 'icheckbox_minimal-blue ingresoEdit',
		    });

			//obtengo el listado de conceptos de cobros
			function listadoConceptos(table)
		    {
				url="/index.php/concepto/listar";
				table.fnClearTable();				
				table.fnReloadAjax(url);			
			}

			//obtengo el id del concetpo que será editado o eliminado
			function obtenerIdConcepto()
			{
				var id="";			
					$('#tableMantenedorConceptoCobro').find('tr.selected').each(function(){
						id=$(this).find('td:first').html();				
					});
				return id;
			}
			
		});

	</script>

</body>
</html>
