<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title><?=$this->nombre_sitio?></title>
<!-- Tell the browser to be responsive to screen width -->
<meta
	content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
	name="viewport">
<!-- Select2 -->
<link rel="stylesheet" href="../../plugins/select2/select2.min.css">
<!-- Bootstrap 3.3.4 -->
<link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet"
	type="text/css" />
<!-- Font Awesome Icons -->
<link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet"
	type="text/css" />
<!-- Ionicons -->
<link href="/ionicons/css/ionicons.min.css" rel="stylesheet"
	type="text/css" />
<!-- DATA TABLES -->
<!-- <link href="/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />-->
<link href="/plugins/datatables/jquery.dataTables.css" rel="stylesheet"
	type="text/css" />
<link href="/plugins/datatables/dataTables.tableTools.css"
	rel="stylesheet">

<link href="/plugins/datatables/dataTables.responsive.css"
	rel="stylesheet" type="text/css" />

<!-- datepicker, estilos calendario -->
<link href="/plugins/datepicker/datepicker3.css" rel="stylesheet"
	type="text/css" />

<!-- iCheck for checkboxes and radio inputs -->
<link href="../../plugins/iCheck/all.css" rel="stylesheet"
	type="text/css" />

<!-- Theme style -->
<link href="/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
<!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
<link href="/dist/css/skins/<?=$this->skin?>.min.css" rel="stylesheet"
	type="text/css" />

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

<style>
.editar {
	width: 20px;
	height: 40px;
	padding: 0px;
	margin: 0px;
}

#formIngresoCobro .error {
	color: Crimson
}
</style>
</head>
<!--
  BODY TAG OPTIONS:
  =================
  Apply one or more of the following classes to get the
  desired effect
  |---------------------------------------------------------|
  | SKINS         | skin-blue                               |
  |               | skin-black                              |
  |               | skin-purple                             |
  |               | skin-yellow                             |
  |               | skin-red                                |
  |               | skin-green                              |
  |---------------------------------------------------------|
  |LAYOUT OPTIONS | fixed                                   |
  |               | layout-boxed                            |
  |               | layout-top-nav                          |
  |               | sidebar-collapse                        |
  |               | sidebar-mini                            |
  |---------------------------------------------------------|
  -->
<body class="<?=$this->skin?> sidebar-mini">
	<div class="wrapper">


		<!-- Main Header -->
      	<?=$this->render('head.phtml') ?>	
  <!-- Fin Main Header -->

		<!-- Left side column. contains the logo and sidebar -->
		<aside class="main-sidebar">

			<!-- sidebar: style can be found in sidebar.less -->
			<section class="sidebar">

				<!-- Sidebar user panel (optional) -->
				<?=$this->render('sidebaruserpanel.phtml') ?>	
		  <!-- Fin Sidebar user panel -->

				<!-- Sidebar Menu -->
				<?=$this->render('menu.phtml') ?>		
        </section>
			<!-- /.sidebar -->
		</aside>

		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			<!-- Main content -->
       
          <?=$this->layout()->content?>
       
        <!-- /.content -->
		</div>
		<!-- /.content-wrapper -->

		<!-- Main Footer -->
			
			<?= $this->render('footer.phtml')?>

      <!-- Control Sidebar -->
		<!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
		<div class="control-sidebar-bg"></div>
	</div>
	<!-- ./wrapper -->

	<!-- REQUIRED JS SCRIPTS -->

	<!-- jQuery 2.1.4 -->
	<script src="/plugins/jQuery/jQuery-2.1.4.min.js"
		type="text/javascript"></script>
	<!-- Bootstrap 3.3.2 JS -->
	<script src="/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<!-- DATA TABES SCRIPT -->
	<script src="/plugins/datatables/jquery.dataTables.min.js"
		type="text/javascript"></script>

	<script src="/plugins/datatables/dataTables.responsive.js"
		type="text/javascript"></script>

	<!-- <script src="/plugins/datatables/dataTables.bootstrap.min.js" type="text/javascript"></script>-->
	<!-- SlimScroll -->
	<script src="/plugins/slimScroll/jquery.slimscroll.min.js"
		type="text/javascript"></script>
	<!-- FastClick -->

	<script src="/plugins/datatables/fnReloadAjax.js" cache="false"></script>
	<script src="/plugins/datatables/dataTables.tableTools.js"
		cache="false"></script>

	<script src="/plugins/fastclick/fastclick.min.js"
		type="text/javascript"></script>
	<!-- AdminLTE App -->
	<script src="/dist/js/app.min.js" type="text/javascript"></script>
	<!-- AdminLTE for demo purposes -->
	<script src="/dist/js/demo.js" type="text/javascript"></script>

	<!-- date-picker -->

	<script src="/plugins/datepicker/bootstrap-datepicker.js"
		type="text/javascript"></script>

	<!-- iCheck 1.0.1 Script checkbox y radiobuttons -->
	<script src="../../plugins/iCheck/icheck.min.js" type="text/javascript"></script>

	<!-- Jquery Validate -->

	<script src="/plugins/jqueryvalidate/jquery.validate.min.js"
		type="text/javascript"></script>
	<script src="/plugins/jqueryvalidate/additional-methods.min.js"
		type="text/javascript"></script>
	<script src="/plugins/jqueryvalidate/messages_es.min.js"
		type="text/javascript"></script>
		
	<!-- JQUERY Number -->
	<script src="/plugins/jquerynumber/jquery.number.js"
		type="text/javascript"></script>
		
	<!-- Select2 -->
	<script src="../../plugins/select2/select2.full.min.js"></script>

	<script type="text/javascript">

	$(function()
	{
		var idRut="<?php echo $_REQUEST['idRut'] ?>";
		var dominio='<?=$this->urlaplicacion?>';
		var valorUF=0;

		fechaActual();		
		
		if(idRut=="")
		{
			window.location.href=dominio+"/index.php/cliente/buscarpornombre";
		}

		obtenerEjecutivos('#ejecutivoSelect');
		obtenerConceptosCobro('#conceptoSelect');
		obtenerFormasPago('#formaPagoSelect');

		obtenerDatosRutCliente(idRut);
		
		obtenerDatosClienteByRut(idRut);

		obtenerUfActual('#valorUfInput',idRut);

		$('#ingresoMontoMoneda').on('focus',function()
		{
			$('#ingresoMontoMoneda').number( true, 0,',','.');	
			$('#ingresoMontoUF').number( true, 1,',','.');	
		});
		
		$('#ingresoMontoUF').on('focus',function()
		{
			$('#ingresoMontoUF').number( true, 1,',','.');
			$('#ingresoMontoMoneda').number( true, 0,',','.');	
		});		

		$('#conceptoSelect').select2();		
		$('#ejecutivoSelect').select2();
		
		$("#formIngresoCobro").validate({
			debug:true,
			rules:{				
				conceptoSelect:{
					required: true
				},	
				golsaInput:{
					required: true
				},
				ingresoMontoUF:{
					required: true
				},	
				ingresoMontoMoneda:{
					required: true
				},						
				dateCobroInput:{
					required: true
				},
				rutSelect:{
					required: true,
				},
				formaPagoSelect:{
					required: true
				},
				ingresoCheck:{
					required: false
				}				
			},
			messages:
			{			
				conceptoSelect:"Debe seleccionar un elemento de la lista.",		
				golsaInput:"Debe ingresar la glosa",	
				ingresoMontoUF:"Debe ingresar el monto en uf",	
				ingresoMontoMoneda:"Debe ingresar el valor en moneda",
				dateCobroInput:"De ingresar la fecha de cobro",
				rutSelect:"Debe ingresar el rut",
				formaPagoSelect:"Debe seleccionar un elemento de la lista",				
			},
			invalidHandler:function(event, validator)
			{
				
			},	
			submitHandler:function(form)
			{		
				if($('#valorUfInput').val()!="")
				{
					url='/index.php/cobroindividual/ingresarcobro';
					
					//si es 2 ingresa a tabla de cobro individual
					var esingreso="2";
					
					if($('.esingreso').hasClass('checked'))
					{
						//si es 1 ingreso a tabla de honorarios
						esingreso="1";						
					}
					
					var datoCobro="idConcepto="+$('#conceptoSelect').val()+
							 	  "&idRut="+idRut+
								  "&glosa="+$('#golsaInput').val()+
							 	  "&montoCobro="+$('#ingresoMontoUF').val()+
							 	  "&observacion="+$('#observacionesInput').val()+
							 	  "&fecha="+$('#dateCobroInput').val()+
							 	  "&idPago="+$('#formaPagoSelect').val()+
							 	  "&esingreso="+esingreso+
							 	  "&valorUF="+valorUF+
							 	  "&valorMoneda="+$('#ingresoMontoMoneda').val();	

					$.ajax({
					    url: url,  
					    type: "POST",
					    data: datoCobro,
					    success: function(datos)
					    {					   					    
							if(datos.registro[0]=='1')
							{
								$('#registroCobroCorrecto').removeClass('hide');
								limpiarControles();
							}
							else if(datos.registro[0]=='2')
							{
								$('#registroCobroIncorrecto').removeClass('hide');
								
							}
					    },
				    	error : function(xhr, status) 
		 			    {
				    		$('#registroCobroIncorrecto').removeClass('hide');
							
		 			    }
					}); 
					
				}
				else
				{
					$('#registrarValorUf').removeClass('hide');	
				}		
			}			
		});

		$('#buttonRegistrarValorUf').on('click',function()
		{
			$('#registrarValorUf').addClass('hide');
		});

		//accion para saber si el concepto elejido es ingreso o no,
		//para que el checkbox de esingreso se seleccione automaticamente.
		$('#conceptoSelect').on('change',function()
		{	
			url="/index.php/concepto/obtener";
			
			var dato="idConcept="+$('#conceptoSelect').val();				
		
			$.ajax({
			    url: url,  
			    type: "POST",
			    data: dato,
			    success: function(datos)
			    {			
					if(datos.concepto[2]=="1")
					{
						$('.esingreso').addClass('checked');
						$('.esingreso').attr({"aria-checked":true});
						
						$('#formaPagoSelect').find('option[value="5"]').attr({"disabled":false});						
						$('#formaPagoSelect').find('option[value="1"],option[value="2"],option[value="3"],option[value="4"]').attr({"disabled":true});

						$('#formaPagoSelect').val(5);
					}
					else
					{
						$('.esingreso').removeClass('checked');
						$('.esingreso').attr({"aria-checked":false});
						$('#formaPagoSelect').attr({"disabled":false});
						
						$('#formaPagoSelect').val('');
						$('#formaPagoSelect').find('option[value="5"]').attr({"disabled":true});			
						$('#formaPagoSelect').find('option[value="1"],option[value="2"],option[value="3"],option[value="4"]').attr({"disabled":false});
						
					}					
			    }
			}); 
			
		});
		
		//accion para transforma la uf en moneda para el valor de mensualidad
		$('#ingresoMontoUF').on('keyup',function()
		{			
			if($('#ingresoMontoUF').val()!='')
			{
				montoUF=(parseFloat(valorUF)*parseFloat($('#ingresoMontoUF').val())).toFixed(0);							
				$('#ingresoMontoMoneda').val(montoUF);

				if(!$('.esingreso').hasClass('checked'))
				{				
					if(parseFloat(montoUF)==0)
					{
						$('#formaPagoSelect').val(6);					
						$('#formaPagoSelect').find('option[value="1"],option[value="2"],option[value="3"],option[value="4"]').attr({"disabled":true});
						$('#formaPagoSelect').find('option[value="6"],option[value="5"]').attr({"disabled":false});
					}
					else
					{
						$('#formaPagoSelect').val('');
						$('#formaPagoSelect').attr({"disabled":false});
						$('#formaPagoSelect').find('option[value="1"],option[value="2"],option[value="3"],option[value="4"]').attr({"disabled":false});
						$('#formaPagoSelect').find('option[value="6"],option[value="5"]').attr({"disabled":true});	
					}
				}
			}
			else
			{
				$('#ingresoMontoMoneda').val('');
			}
		});
		
		//accion para transforma el valor monetario de la mensualidad a uf
		$('#ingresoMontoMoneda').on('keyup',function()
		{			
			if($('#ingresoMontoMoneda').val()!='')
			{
				montoMoneda=$(this).val();			
				$('#ingresoMontoUF').val((parseFloat($('#ingresoMontoMoneda').val())/parseFloat(valorUF)).toFixed(2));

				if(!$('.esingreso').hasClass('checked'))
				{
					if(parseFloat(montoMoneda)==0)
					{
						$('#formaPagoSelect').val(6);					
						$('#formaPagoSelect').find('option[value="1"],option[value="2"],option[value="3"],option[value="4"]').attr({"disabled":true});
						$('#formaPagoSelect').find('option[value="6"],option[value="5"]').attr({"disabled":false});
					}
					else
					{
						$('#formaPagoSelect').val('');					
						$('#formaPagoSelect').attr({"disabled":false});
						$('#formaPagoSelect').find('option[value="1"],option[value="2"],option[value="3"],option[value="4"]').attr({"disabled":false});
						$('#formaPagoSelect').find('option[value="6"],option[value="5"]').attr({"disabled":true});	
					}
				}
				
			}
			else
			{
				$('#ingresoMontoUF').val('');
			}
		});

		$('#buttonRegistroCobroCorrecto').on('click',function()
		{
			$('#registroCobroCorrecto').addClass('hide');
		});

		$('#buttonRegistroCobroIncorrecto').on('click',function()
		{
			$('#registroCobroIncorrecto').addClass('hide');
		});
		
		$('#ingresoCheck').iCheck({
	       checkboxClass: 'icheckbox_minimal-blue esingreso',
	    });

	    $('#buttonActualizarUF').on('click',function()
	   	{
		   	$('#actualizarUF').addClass('hide');
		});

		function limpiarControles()
		{
			$('.control').val('');
			$('.esingreso').removeClass('checked');
		  	$('.esingreso').attr({"aria-checked":false});
		}

		$('#dateCobroInput').on('changeDate',function()
		{
			fecha=$('#dateCobroInput').val().toString().split('-');
			
			url="/index.php/valores/obteneruf";

			data="anioUf="+$.trim(fecha['2'].toString())+"&mesUf="+$.trim(fecha['1'].toString());

			fecha="";

			objetivo='#valorUfInput';
			
			$(objetivo).empty();

			$('<option>').
			attr({value:"0"}).
			text('Seleccione').
			prop({disabled: false}).
			appendTo(objetivo);

			$.ajax({
			    url: url,  
			    type: "POST",
			    data: data,  
			    async:false,
			    success: function(datos)
			   	{		 				  
			    	if(datos.valoruf.length>0)
			    	{
						$('<option selected="selected">').
						attr({value:datos.valoruf[1]}).
						text("$ "+datos.valoruf[0]).
						appendTo(objetivo);
						
						$('#buttonCobroIndividual').attr({"disabled":false});

						$('#actualizarUF').addClass('hide');

						valorUF=parseFloat(datos.valoruf[0]);

						$('#ingresoMontoUF').val('');
						$('#ingresoMontoMoneda').val('');
			    	
				    }
				    else
				    {
				    	 $('<option selected="selected">').
						 attr({value:'sinuf'}).
						 text("Sin Uf").
						 appendTo(objetivo);

						 $('#actualizarUF').removeClass('hide');
						   
						 $('#buttonCobroIndividual').attr({"disabled":true});
				    }
		 	    }
			}); 
		});

		$('#dateCobroInput').datepicker({
			autoclose:true
		});
	    
	    //obtengo los ejecutivos regitrados
	    function obtenerEjecutivos(objetivo)
		{				
		    url = '/index.php/usuario/listar';
		    
			$(objetivo).empty();			
					
			$('<option>').
			attr({value:""}).
			text('Seleccione').
			prop({disabled: false}).
			appendTo(objetivo);

			var dato="";
		
			$.ajax({
			    url: url,  
			    type: "POST",
			    data: dato, 
			    async:false,
			    success: function(datos){
				    
			    	 $.each(datos.data, function( index, value ) {
							
						 $('<option>').
						   prop({value:value[0]}).
						   text(value[1]).
						   appendTo(objetivo);
					});
			    }
			}); 			
		}

	    //obtengo los conceptos de cobro
	    function obtenerConceptosCobro(objetivo)
		{				
		    url = '/index.php/concepto/listar';
		    
			$(objetivo).empty();			
					
			$('<option>').
			attr({value:""}).
			text('Seleccione').
			prop({disabled: false}).
			appendTo(objetivo);

			var dato="";
		
			$.ajax({
			    url: url,  
			    type: "POST",
			    data: dato, 
			    success: function(datos){
				    
			    	 $.each(datos.data, function( index, value ) 
					 {
			    		 if(value[0]!='4' && value[0]!='5')
			    		 {
			    			 $('<option>').
							   prop({value:value[0]}).
							   text(value[1]).
							   appendTo(objetivo); 
			    		 }							
					});
			    }
			}); 			
		}

	    //obtengo los los datos del cliente segun el rut seleccionado
	    function obtenerDatosClienteByRut(idRuts)
		{				
		    url = '/index.php/cliente/obtenerbyrut';

			var dato="idRut="+idRuts;
		
			$.ajax({
			    url: url,  
			    type: "POST",
			    data: dato,
			    async:false,
			    success: function(datos)
			    {					  
					$('#nombreClienteInput').val(datos.cliente[0]);	
					$('#ejecutivoSelect').val(datos.cliente[1]);	
			    }
			}); 			
		}

	    //obtengo los los datos del rut segun el rut seleccionado
	    function obtenerDatosRutCliente(idRuts)
		{				
		    url = '/index.php/rut/obtenerrubyid';

			var dato="idRut="+idRuts;
		
			$.ajax({
			    url: url,  
			    type: "POST",
			    data: dato,
			    success: function(datos)
			    {					    					
					$('#razonSocialRut').val(datos.rut[3]);	
					$('#rutCliente').val(datos.rut[4]);	
			    }
			}); 			
		}

	  	//Obtengo formas de pago 
	    function obtenerFormasPago(objetivo)
		{				
		    url = '/index.php/cobroindividual/obtenerformapago';
		    
			$(objetivo).empty();			
					
			$('<option>').
			attr({value:""}).
			text('Seleccione').
			prop({disabled: false}).
			appendTo(objetivo);

			var dato="";
		
			$.ajax({
			    url: url,  
			    type: "POST",
			    data: dato, 
			    success: function(datos){

			    	$.each(datos.formapago, function( index, value ) {
						
						 $('<option>').
						   prop({value:value[0]}).
						   text(value[1]).
						   appendTo(objetivo);
					});	
			    }
			}); 			
		}

		function obtenerUfActual(objetivo,idRuts)
		{
			url = '/index.php/valores/obtenerufactual';

			var dato="idRut="+idRuts;

			$.ajax({
 			    url: url,  
 			    type: "POST",
 			    data: dato, 
 			    success: function(datos)
 			    {
					if(datos.valoruf.length>0)
					{
						$(objetivo).empty();		
	 	    			
	 	    			$('<option>').
	 	    			attr({value:datos.valoruf[0]}).
	 	    			text("$ "+datos.valoruf[1]).
	 	    			prop({disabled: false}).
	 	    			appendTo(objetivo); 

	 	    			valorUF=parseFloat(datos.valoruf[1]);
	 	    			
					}
					else
					{
						$(objetivo).empty();		
	 	    			
	 	    			$('<option>').
	 	    			attr({value:""}).
	 	    			text("Sin UF").
	 	    			prop({disabled: false}).
	 	    			appendTo(objetivo); 
					}
 			    },
 			   	error : function(xhr, status) 
			    {
			    	
			    }
 			}); 
			
		}
		
	    function fechaActual()
		{
			var d = new Date();

			var month = d.getMonth()+1;
			var day = d.getDate();			

			var fecha =  (day<10 ? '0' : '') + day + '-' +(month<10 ? '0' : '') + month + '-' +d.getFullYear();

			$('#dateCobroInput').val(fecha);
		    
		}  
		


	});
	
	</script>



</body>
</html>
