<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title><?=$this->nombre_sitio?></title>
<!-- Tell the browser to be responsive to screen width -->
<meta
	content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
	name="viewport">
<!-- Select2 -->
<link rel="stylesheet" href="../../plugins/select2/select2.min.css">
<!-- Bootstrap 3.3.4 -->
<link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet"
	type="text/css" />
<!-- Font Awesome Icons -->
<link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet"
	type="text/css" />
<!-- Ionicons -->
<link href="/ionicons/css/ionicons.min.css" rel="stylesheet"
	type="text/css" />
<!-- DATA TABLES -->
<!-- <link href="/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />-->
<link href="/plugins/datatables/jquery.dataTables.css" rel="stylesheet"
	type="text/css" />
<link href="/plugins/datatables/dataTables.tableTools.css"
	rel="stylesheet">

<link href="/plugins/datatables/dataTables.responsive.css"
	rel="stylesheet" type="text/css" />

<!-- Theme style -->
<link href="/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
<!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
<link href="/dist/css/skins/<?=$this->skin?>.min.css" rel="stylesheet"
	type="text/css" />

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

<style>
.editar {
	width: 20px;
	height: 40px;
	padding: 0px;
	margin: 0px;
}

#formBuscarCliente .error {
	color: Crimson
}
</style>
</head>
<!--
  BODY TAG OPTIONS:
  =================
  Apply one or more of the following classes to get the
  desired effect
  |---------------------------------------------------------|
  | SKINS         | skin-blue                               |
  |               | skin-black                              |
  |               | skin-purple                             |
  |               | skin-yellow                             |
  |               | skin-red                                |
  |               | skin-green                              |
  |---------------------------------------------------------|
  |LAYOUT OPTIONS | fixed                                   |
  |               | layout-boxed                            |
  |               | layout-top-nav                          |
  |               | sidebar-collapse                        |
  |               | sidebar-mini                            |
  |---------------------------------------------------------|
  -->
<body class="<?=$this->skin?> sidebar-mini">
	<div class="wrapper">


		<!-- Main Header -->
      	<?=$this->render('head.phtml') ?>	
  <!-- Fin Main Header -->

		<!-- Left side column. contains the logo and sidebar -->
		<aside class="main-sidebar">

			<!-- sidebar: style can be found in sidebar.less -->
			<section class="sidebar">

				<!-- Sidebar user panel (optional) -->
				<?=$this->render('sidebaruserpanel.phtml') ?>	
		  <!-- Fin Sidebar user panel -->

				<!-- Sidebar Menu -->
				<?=$this->render('menu.phtml') ?>		
        </section>
			<!-- /.sidebar -->
		</aside>

		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			<!-- Main content -->
       
          <?=$this->layout()->content?>
       
        <!-- /.content -->
		</div>
		<!-- /.content-wrapper -->

		<!-- Main Footer -->
			
			<?= $this->render('footer.phtml')?>

      <!-- Control Sidebar -->
		<!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
		<div class="control-sidebar-bg"></div>
	</div>
	<!-- ./wrapper -->

	<!-- REQUIRED JS SCRIPTS -->

	<!-- jQuery 2.1.4 -->
	<script src="/plugins/jQuery/jQuery-2.1.4.min.js"
		type="text/javascript"></script>
	<!-- Bootstrap 3.3.2 JS -->
	<script src="/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<!-- DATA TABES SCRIPT -->
	<script src="/plugins/datatables/jquery.dataTables.min.js"
		type="text/javascript"></script>

	<script src="/plugins/datatables/dataTables.responsive.js"
		type="text/javascript"></script>

	<!-- <script src="/plugins/datatables/dataTables.bootstrap.min.js" type="text/javascript"></script>-->
	<!-- SlimScroll -->
	<script src="/plugins/slimScroll/jquery.slimscroll.min.js"
		type="text/javascript"></script>
	<!-- FastClick -->

	<script src="/plugins/datatables/fnReloadAjax.js" cache="false"></script>
	<script src="/plugins/datatables/dataTables.tableTools.js"
		cache="false"></script>

	<script src="/plugins/fastclick/fastclick.min.js"
		type="text/javascript"></script>
	<!-- AdminLTE App -->
	<script src="/dist/js/app.min.js" type="text/javascript"></script>
	<!-- AdminLTE for demo purposes -->
	<script src="/dist/js/demo.js" type="text/javascript"></script>
	<!-- page script -->


	<!-- Jquery Validate -->

	<script src="/plugins/jqueryvalidate/jquery.validate.min.js"
		type="text/javascript"></script>
	<script src="/plugins/jqueryvalidate/additional-methods.min.js"
		type="text/javascript"></script>
	<script src="/plugins/jqueryvalidate/messages_es.min.js"
		type="text/javascript"></script>
		
	<!-- Select2 -->
	<script src="../../plugins/select2/select2.full.min.js"></script>

	<script type="text/javascript">

	$(function(){

		//inicializo dataTable
		var tableListadoClientes = $('#tableListadoClientes').dataTable( {
	        dom: 'T<"clear">lfrtip',
	        bFilter: true,
	        "responsive":true,
	        "bLengthChange": false,
	        "autoWidth": false,	      
	        tableTools: {
	            "sSwfPath": "/swf/copy_csv_xls_pdf.swf",
	            "sRowSelect": "single",
	            "aButtons": [ ]
	        },
	        "language": {
				"lengthMenu": "Desplegando _MENU_ registros por p&aacute;gina",
				"zeroRecords": "Nada encontrado - Lo sentimos",
				"info": "Mostrando p&aacute;gina _PAGE_ de _PAGES_",
				"infoEmpty": "No hay registros disponibles",
				"infoPostFix":    "",
				"thousands":      ",",
				"loadingRecords": "Cargando...",
				"processing":     "Procesando...",
				"search":         "Buscar:",
				"infoFiltered ": "(Filtrando de un total de _MAX_ registros)",
				"paginate": {
					"first":      "Primero",
					"last":       "&Uacute;ltimo",
					"next":       "Siguiente",
					"previous":   "Anterior"
					}
				}		
	        
	    } );

		//ejecuto funcion para obtener el listado total de clientes
		listadoClientes(tableListadoClientes);

		//ejecuto funcion para cargar los ejecutivos en combobox
		obtenerEjecutivos();

		var id_user = '<?= $this->id_usuario ?>';
		var perfil=<?= $this->rol ?>;
		
		switch(perfil)
		{
			case 1:	
				$('#ejecutivoSelect').val(id_user);
				$('#ejecutivoSelect').attr({"disabled":true});
				listadoClientesByEjecutivo(tableListadoClientes,$('#ejecutivoSelect').val());
			break;
									
		}					

		$('#ejecutivoSelect').select2();	

		//valido formulario de busqueda de cliente	
		$("#formBuscarCliente").validate({
			debug:true,
			rules:{
				nombreClienteInput:{
					required:false
				},
				ejecutivoSelect:{
					required: false
				},								
			},
			messages:{
				nombreClienteInput:"Debe ingresar un nombre.",
				ejecutivoSelect:"Debe seleccionar un elemento de la lista.",				
			},
			invalidHandler:function(event, validator)
			{
				
			},	
			submitHandler:function(form)
			{
				url="/index.php/cliente/listarbynombrecliente?idEjecutivo="+$('#ejecutivoSelect').val()+"&nombreCliente="+$('#nombreClienteInput').val();
				tableListadoClientes.fnClearTable();				
				tableListadoClientes.fnReloadAjax(url);	
			}			
		});
		
		//direcciono a la vista detalle del cliente, con el id del cliente seleccionado.
		$('#irDetalleCliente').on('click',function()
		{
			if($('#tableListadoClientes tbody tr').hasClass('selected'))
			{
				var idCliente = obtenerIdCliente();
				$('#idCliente').val(idCliente);
				$('#formdetalle').submit();
			}
			else
			{
				$('#seleccionaConceptoLista').removeClass('hide');
			}
			
		});

		//cierro el mensage de aviso, de seleccion de usuario
		$('#buttonCierraMsgSeleccion').on('click',function()
		{
			$('#seleccionaConceptoLista').addClass('hide');
		});

		//funcion para obtener los clientes asociados a cada ejecutivo
		function listadoClientesByEjecutivo(table,idEjecutivo)
		{
			url="/index.php/cliente/listarbyejecutivo?idUsuario="+idEjecutivo;
			table.fnClearTable();				
			table.fnReloadAjax(url);
		}

		//funcion para obtener el total de los clientes
		function listadoClientes(table)
	    {
			url="/index.php/cliente/listar";
			table.fnClearTable();				
			table.fnReloadAjax(url);			
		}

		//funcion para obtener a los ejecutvos y cargarlos al combobox
		function obtenerEjecutivos()
		{				
		    url = '/index.php/usuario/listar';
		    
			$('#ejecutivoSelect').empty();
						
			objetivo = "#ejecutivoSelect";
					
			$('<option>').
			attr({value:""}).
			text('Seleccione').
			prop({disabled: false, selected: true}).
			appendTo(objetivo);

			var dato="";
		
			$.ajax({
			    url: url,  
			    type: "POST",
			    data: dato,  
			    async:false,
			    success: function(datos){
				    
			    	 $.each(datos.data, function( index, value ) {
							
						 $('<option>').
						   prop({value:value[0]}).
						   text(value[1]).
						   appendTo(objetivo);
					});	
			    }
			}); 
			
		}

		//funcion para obtener el id del usuario listado en el dataTable
		function obtenerIdCliente()
		{
			var id="";			
				$('#tableListadoClientes').find('tr.selected').each(function(){
					id=$(this).find('td:first').html();				
				});
			return id;
		}
	});	
	
	</script>
</body>
</html>
