<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title><?=$this->nombre_sitio?></title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.4 -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="/ionicons/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- DATA TABLES -->
    <!-- <link href="/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />-->
    <link href="/plugins/datatables/jquery.dataTables.css" rel="stylesheet" type="text/css" />
    <link href="/plugins/datatables/dataTables.tableTools.css" rel="stylesheet">
      
   
    <link href="/plugins/datatables/dataTables.responsive.css" rel="stylesheet" type="text/css" />
    <link href="/plugins/select2/select2.min.css" rel="stylesheet" type="text/css" /> 
 <!-- daterange picker -->
    <link href="/plugins/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
    <!-- iCheck for checkboxes and radio inputs -->
    <link href="/plugins/iCheck/all.css" rel="stylesheet" type="text/css" />
    <!-- Bootstrap Color Picker -->
    <link href="/plugins/colorpicker/bootstrap-colorpicker.min.css" rel="stylesheet" type="text/css" />
    <!-- Bootstrap time Picker -->
    <link href="/plugins/timepicker/bootstrap-timepicker.min.css" rel="stylesheet" type="text/css" />
    <!-- Select2 -->
   
   
   
   

 
    <!-- Theme style -->
    <link href="/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link href="/dist/css/skins/<?=$this->skin?>.min.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
  <style>
  	.editar{
  		width:20px;
  		height:40px;
  		padding:0px;
  		margin:0px;
  	}
 

    
  </style>  
  </head>
  <!--
  BODY TAG OPTIONS:
  =================
  Apply one or more of the following classes to get the
  desired effect
  |---------------------------------------------------------|
  | SKINS         | skin-blue                               |
  |               | skin-black                              |
  |               | skin-purple                             |
  |               | skin-yellow                             |
  |               | skin-red                                |
  |               | skin-green                              |
  |---------------------------------------------------------|
  |LAYOUT OPTIONS | fixed                                   |
  |               | layout-boxed                            |
  |               | layout-top-nav                          |
  |               | sidebar-collapse                        |
  |               | sidebar-mini                            |
  |---------------------------------------------------------|
  -->
  <body class="<?=$this->skin?> sidebar-mini">
    <div class="wrapper">

      
  <!-- Main Header -->
      	<?=$this->render('head.phtml') ?>	
  <!-- Fin Main Header -->    	

      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">

          <!-- Sidebar user panel (optional) -->
				<?=$this->render('sidebaruserpanel.phtml') ?>	
		  <!-- Fin Sidebar user panel -->
		  
          <!-- Sidebar Menu -->
				<?=$this->render('menu.phtml') ?>		
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <!-- Main content -->
       
          <?=$this->layout()->content?>
       
        <!-- /.content -->
      </div><!-- /.content-wrapper -->

      <!-- Main Footer -->
			
			<?= $this->render('footer.phtml') ?>

      <!-- Control Sidebar -->
      <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
      <div class="control-sidebar-bg"></div>
    </div><!-- ./wrapper -->

    <!-- REQUIRED JS SCRIPTS -->

    <!-- jQuery 2.1.4 -->
    <script src="/plugins/jQuery/jQuery-2.1.4.min.js" type="text/javascript"></script>
    <link href = "/plugins/JqueryAlerts/jquery.alerts.css" rel = "stylesheet">    
	<script src = "/plugins/jQuery/jquery-migrate-1.2.1.js" type = "text/javascript"></script>
	<script src = "/plugins/JqueryAlerts/jquery.alerts.js" type = "text/javascript"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- DATA TABES SCRIPT -->
    <script src="/plugins/datatables/jquery.dataTables.min.js" type="text/javascript"></script>    
    <script src="/plugins/datatables/dataTables.responsive.js" type="text/javascript"></script>
	<script src="/plugins/datatables/fnReloadAjax.js" cache="false"></script>
	<script src="/plugins/datatables/dataTables.tableTools.js" cache="false"></script>
    
    <!-- <script src="/plugins/datatables/dataTables.bootstrap.min.js" type="text/javascript"></script>-->
    <!-- SlimScroll -->
    <script src="/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src="/plugins/fastclick/fastclick.min.js" type="text/javascript"></script>
    <!-- Select2 -->
    <script src="/plugins/select2/select2.full.min.js" type="text/javascript"></script>
    <!-- InputMask -->
    <script src="/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
    <script src="/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
    <script src="/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
    <!-- date-range-picker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js" type="text/javascript"></script>
    <script src="/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
    <!-- bootstrap color picker -->
    <script src="/plugins/colorpicker/bootstrap-colorpicker.min.js" type="text/javascript"></script>
    <!-- bootstrap time picker -->
    <script src="/plugins/timepicker/bootstrap-timepicker.min.js" type="text/javascript"></script>
    <!-- SlimScroll 1.3.0 -->
    <script src="/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- iCheck 1.0.1 -->
    <script src="/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src="/plugins/fastclick/fastclick.min.js" type="text/javascript"></script>

<!-- AdminLTE App -->
    <script src="/dist/js/app.min.js" type="text/javascript"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/dist/js/demo.js" type="text/javascript"></script>
    <!-- page script -->
    <script type="text/javascript">
    
$(function () {
      	  //Initialize Select2 Elements
          $(".select2").select2();

          //Datemask dd/mm/yyyy
          $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
          //Datemask2 mm/dd/yyyy
          $("#datemask2").inputmask("mm/dd/yyyy", {"placeholder": "mm/dd/yyyy"});
          //Money Euro
          $("[data-mask]").inputmask();

          //Date range picker
          $('#reservation').daterangepicker();
          //Date range picker with time picker
          $('#reservationtime').daterangepicker({timePicker: true, timePickerIncrement: 30, format: 'MM/DD/YYYY h:mm A'});
          //Date range as a button
          $('#daterange-btn').daterangepicker(
                  {
                    ranges: {
                      'Today': [moment(), moment()],
                      'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                      'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                      'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                      'This Month': [moment().startOf('month'), moment().endOf('month')],
                      'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                    },
                    startDate: moment().subtract(29, 'days'),
                    endDate: moment()
                  },
          function (start, end) {
            $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
          }
          );

          //iCheck for checkbox and radio inputs
          $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
            checkboxClass: 'icheckbox_minimal-blue',
            radioClass: 'iradio_minimal-blue'
          });
          //Red color scheme for iCheck
          $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
            checkboxClass: 'icheckbox_minimal-red',
            radioClass: 'iradio_minimal-red'
          });
          //Flat red color scheme for iCheck
          $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
            checkboxClass: 'icheckbox_flat-green',
            radioClass: 'iradio_flat-green'
          });

          //Colorpicker
          $(".my-colorpicker1").colorpicker();
          //color picker with addon
          $(".my-colorpicker2").colorpicker();

          //Timepicker
          $(".timepicker").timepicker({
            showInputs: false
          });
});


function cargaCombos(){

    url = '/index.php/usuario/listadovendedoresjson';
    var datos = "";
	objetivo = ".vendedor";
	$('.vendedor').empty();

	$('<option>').
	attr({value: ""}).
	text('Seleccione un vendedor').
	prop({disabled: false, selected: true}).
	appendTo('.vendedor');

	$.ajax({ 
	    url: url, 
	    dataType: 'json', 
	    data: datos, 
	    async: false, 
	    success: function(datos){ 
	    	if(datos.length < 1){
				jAlert("No se encontraron Lineas de Negocios","Alerta Sargent");
				return;
			}
			//Por cada dato, se agrega como opcion
			$(datos).each(function(i, dato){
				$('<option>').
				attr({value: dato.id}).
				text(dato.nombre).
				appendTo(objetivo);
			});
	    } 
	});  

	$(".lineadenegocios").on('change keyup', function(){
		if($(this).val() == ""){
			return;
		}
		var number = $(this).attr('id').split('_');
		//llena combo de categorias
		url = '/index.php/categoria/listadocategoriasjson';
		var datos =  "id_lineanegocio="+$(this).val();
		objetivo = ".categoria";
		$('.categoria').empty();
		$('<option>').
		attr({value: ""}).
		text('Seleccione una Categoria').
		prop({disabled: false, selected: true}).
		appendTo('.categoria');
		
		$.ajax({
		    url: url, 
		    dataType: 'json', 
		    data: datos, 
		    async: false, 
		    success: function(datos){ 
		    	if(datos.length < 1){
					jAlert("No se encontraron Categorias","Alerta Sargent");
					return;
				}
				//Por cada dato, se agrega como opcion
				$(datos).each(function(i, dato){
					$('<option>').
					attr({value: dato.id}).
					text(dato.nombre).
					appendTo(objetivo);
				});
		    } 
		});
	});

	$(".categoria").on('change keyup', function(){
		if($(this).val() == ""){
			return;
		}
		var number = $(this).attr('id').split('_');
		//llena combo de sub categorias
		url = '/index.php/subcategoria/listadosubcategoriasjson';
		var datos = "id_categoria="+$(this).val();
		objetivo = ".subcategoria";
		$('.subcategoria').empty();
		$('<option>').
		attr({value: ""}).
		text('Seleccione una Sub Categoria').
		prop({disabled: false, selected: true}).
		appendTo('.subcategoria');
		
		$.ajax({ 
		    url: url, 
		    dataType: 'json', 
		    data: datos, 
		    async: false, 
		    success: function(datos){ 
		    	if(datos.length < 1){
					jAlert("No se encontraron Sub Categorias","Alerta Sargent");
					return;
				}
				//Por cada dato, se agrega como opcion
				$(datos).each(function(i, dato){
					$('<option>').
					attr({value: dato.id}).
					text(dato.nombre).
					appendTo(objetivo);
				});
		    } 
		}); 


		
	});



	//llena combo de linea de negocios
    url = '/index.php/lineanegocio/listadolineasjson';
    var datos = "";
	objetivo = ".lineadenegocios";
	$('.lineadenegocios').empty();

	$('<option>').
	attr({value: ""}).
	text('Seleccione una Linea de Negocio').
	prop({disabled: false, selected: true}).
	appendTo('.lineadenegocios');

	$.ajax({ 
	    url: url, 
	    dataType: 'json', 
	    data: datos, 
	    async: false, 
	    success: function(datos){ 
	    	if(datos.length < 1){
				jAlert("No se encontraron Lineas de Negocios","Alerta Sargent");
				return;
			}
			//Por cada dato, se agrega como opcion
			$(datos).each(function(i, dato){
				$('<option>').
				attr({value: dato.id}).
				text(dato.nombre).
				appendTo(objetivo);
			});
	    } 
	});    	






}

$(document).ready(function() {	    


	var table = $('#example1').dataTable( {
        dom: 'T<"clear">lfrtip',
        bFilter: false,
        "responsive":true,
        "bLengthChange": false,
        "autoWidth": false,
        tableTools: {
            "sSwfPath": "/swf/copy_csv_xls_pdf.swf",
            "aButtons": [
                       { sExtends: "csv",
                         sFileName: 'proyectos.csv',
                         sFieldSeperator: ",",
                         sButtonClass: 'btn btn-danger' 
                       },
                       { sExtends: "xls",
                         sFileName: 'proyectos.xls',
                         sButtonClass:'btn btn-success'
                         
                       }/*,
                       { sExtends: "pdf",
                         sFileName: 'proyectos.pdf',
                         sButtonClass:'btn btn-warning'
                       }  */ 
                   ] 
        },
        "language": {
			"lengthMenu": "Desplegando _MENU_ registros por p&aacute;gina",
			"zeroRecords": "Nada encontrado - Lo sentimos",
			"info": "Mostrando p&aacute;gina _PAGE_ de _PAGES_",
			"infoEmpty": "No hay registros disponibles",
			"infoPostFix":    "",
			"thousands":      ",",
			"loadingRecords": "Cargando...",
			"processing":     "Procesando...",
			"search":         "Buscar:",
			"infoFiltered ": "(Filtrando de un total de _MAX_ registros)",
			"paginate": {
				"first":      "Primero",
				"last":       "&Uacute;ltimo",
				"next":       "Siguiente",
				"previous":   "Anterior"
				}
			}
        
    } );

			    
   cargaCombos();

      			
      			
   $("#generar").on('click', function(){

	   table.fnClearTable();
	
		var vendedor = $('#vendedor').val();
		var linea = $('#lineadenegocios').val();
		var categoria = $('#categoria').val();
		var subcategoria = $('#subcategoria').val();
		var url = "/index.php/proyecto/buscarxfiltros?";
	
		url +="vendedor="+vendedor;
		url +="&linea="+linea;
		url +="&categoria="+categoria;
		url +="&subcategoria="+subcategoria;
		table.fnReloadAjax(url);
      	    	    	
	});
      			
   		
});


    </script>
  </body>
</html>
