<section class="content-header">
          <h1>
            Proyectos
            <small>Informaci&oacute;n de Proyectos</small>
          </h1>
          <ol class="breadcrumb">
            <li class="active">Home</li>
          </ol>
</section>
 <section class="content">
<div class="row">
            <div class="col-xs-12">
              <div class="box">
                <div class="box-header">
                  <!--<h3 class="box-title">Informaci&oacute;n de Mis Proyectos</h3>-->
                </div><!-- /.box-header -->
                <div class="box-body">            
                  <!-- <table id="example1" class="table table-bordered table-hover">-->
                  <table id="example1" class="table table-bordered responsive nowrap" cellspacing="0" width="100%">
                  <!-- <table id="example1" class=" table table-striped table-hover dt-responsive" cellspacing="0" width="100%">-->                 
                    <thead>
                      <tr>
                      	  <th>Nombre</th>
	                      <th>Datos y Antecedentes</th>
	                      <th>Vendedor</th>
	                      <th>Fecha Creaci&oacute;n</th>
	                      <th>Sin Avance</th>
						  <th>Pc</th>
						  <th>Acci&oacute;n</th>
                      </tr>
                    </thead>
                    <tbody>
<?php 
foreach($this->proyectos as $key => $proyecto)
{ 
?>                  
     				<tr>
                      	  <td><?=$proyecto['lc05_tituloProyecto']?></td>
						  <td>					  
						  	<div style="width:200px;white-space:initial;"><?=$proyecto['lc05_descripcionProyecto']?></div>				  
						  </td>
						  <td><?=$proyecto['lc01_nombreUsuario']?></td>
						  <td><?=$proyecto['fechaCreacion']?></td>
						  <?php
						  // si los dias sin avance estan entre 0 y 5 pintamos de color verde
						  // si los dias sin avance estan entre 5 y 10 pintamos de color azul
						  // si los dias sin avance estan entre 10 y 15 pintamos de amarillo
						  // si los dias sin avance son superior a 15 pintamos de color rojo
						  $label="";
						  
						  if($proyecto['diasSinAvance'] <=5 ){
						  	$label = "label label-success";						  	
						  }elseif($proyecto['diasSinAvance'] > 5 && $proyecto['diasSinAvance'] <= 10){
						  	$label = "label label-primary";
						  }elseif($proyecto['diasSinAvance'] > 10 && $proyecto['diasSinAvance'] <= 15){
						  	$label = "label label-warning";
						  }elseif($proyecto['diasSinAvance'] > 15){
						  	$label = "label label-danger";
						  }
						  
						  
						  ?>
						  <td><span class="<?=$label?>"><?=$proyecto['diasSinAvance']?> d&iacute;as</span></td>                   
						  <td><span class="badge bg-red"><?=$proyecto['score']?>%</span></td>
						  <td>
						  	<a href="/index.php/proyecto/grafico?id=<?=$proyecto['lc05_idProyecto']?>" class="btn btn-app editar">
		                    	<i class="fa fa-area-chart"></i> Ver
		                  	</a>
		                  </td>
                      </tr>  
<?php 
}
?>             

                    </tbody>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
</div><!-- /.row -->
 </section>