<section class="content-header">

	<h1>PEC, Autopago y S/M</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-credit-card"></i>Verificaci&oacute;n
				PEC y Autopago</a></li>
		<li class="active">PEC, Autopago y S/M</li>
	</ol>

</section>

<section class="content">

	<div class="box box-primary">

		<div class="box-header with-border">
			<h3 class="box-title">
				<strong>Verificar PEC y Autopago</strong>
			</h3>

		</div>

		<form role="form" action="" id="formVerificaPecAutoPago">


			<div class="box-body">
				<div class="form-group">
					<label for="ejecutivoOrdenPagoSelect">Ejecutivo</label> <select
						class="form-control control control" id="ejecutivoOrdenPagoSelect"
						name="ejecutivoOrdenPagoSelect">
					</select>
				</div>

				<div class="form-group">
					<label for="clienteVerificaPagoSelect">Clientes</label> <select
						class="form-control control" id="clienteVerificaPagoSelect"
						name="clienteVerificaPagoSelect">
						<option value="">Seleccione</option>
					</select>
				</div>

				<div class="form-group">
					<label for="rutVerificaPagoSelect">Ruts Del Cliente</label> <select
						class="form-control control" id="rutVerificaPagoSelect"
						name="rutVerificaPagoSelect">
						<option value="">Seleccione</option>
					</select>
				</div>

				<div class="form-group">
					<label>Seleccione una fecha de inicio y termino</label> <input
						type="text" placeholder="dd/mm/yyyy - dd/mm/yyyy"
						class="form-control pull-right control" id="fechaDesdeHasta"
						name="fechaDesdeHasta">
				</div>


			</div>


			<div class="box-footer">
				<button type="submit" class="btn btn-primary">
					Buscar <span class="fa fa-search"></span>
				</button>
			</div>
		</form>

	</div>

	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title">
				<strong>Resultados</strong>
			</h3>
		</div>

		<div class="box-body">

			<div class="from-group">
				<table class="table table-bordered table-hover cell-border compact display"
					id="tablaVerificarPagos">
					<thead>
						<th>Id</th>
						<th>Tipo</th>
						<th>Fecha</th>
						<th>Glosa</th>
						<th>N&uacute;mero Sociedad</th>
						<th>RUT Asociado</th>
						<th>Monto Cobrado</th>
						<th>N&uacute;mero Folio</th>
						<th>Estado</th>
						<th>Forma de Pago</th>
					</thead>
				</table>
			</div>
			<br>

			<div class="form-group hide" id="mensajeSeleccioneCobro">
				<div class="alert alert-warning alert-dismissable">
					<button type="button" class="close"
						id="buttonMensajeSeleccioneCobro" aria-hidden="true">&times;</button>
					<h4>
						<i class="icon fa fa-warning"></i> Ops !
					</h4>
					<p>Primero debe seleccionar un cobro</p>
				</div>
			</div>
			
			<div class="form-group hide" id="mensajeCobroVerificado">
				<div class="alert alert-warning alert-dismissable">
					<button type="button" class="close"
						id="buttonMensajeCobroVerificado" aria-hidden="true">&times;</button>
					<h4>
						<i class="icon fa fa-warning"></i> Ops !
					</h4>
					
					<p>El cobro ya se encuentra verificado</p>
				
				</div>
			</div>

			<div class="form-group hide" id="registroFolioCorrecto">
				<div class="alert alert-success alert-dismissable">
					<button type="button" class="close"
						id="buttonRegistroFolioCorrecto" aria-hidden="true">&times;</button>
					<h4>
						<i class="icon fa fa-check"></i> Ok!
					</h4>

					<p>Registro n&uacute;mero de folio correcto</p>

				</div>
			</div>

			<div class="form-group hide" id="errorAccion">
				<div class="alert alert-danger alert-dismissable">
					<button type="button" class="close" id="buttonErrorAccion"
						aria-hidden="true">&times;</button>
					<h4>
						<i class="icon fa fa-remove"></i> Ops !
					</h4>

					<p>Problemas al realizar la acci&oacute;n</p>

				</div>
			</div>

		</div>

		<div class="box-footer">

			<button type="button" class="btn btn-primary" id="buttonVerificaPec">
				Verificar Pago <span class="fa fa-check"></span>
			</button>
		</div>

	</div>

</section>

<!---------- Ventanas Modales ---------->

<!-- Modal verificacion PEC Autopago -->
<div class="modal modal-success fade" id="modalVerificaPec">

	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title">
					<strong>Ingresar Verificaci&oacute;n</strong>
				</h4>
			</div>
			<form role="form" action="" id="formVerificaFolioPecAutoPago">

				<div class="modal-body">

					<div class="form-group">
						<label for="folioVerificacionPagoInput">Folio Cup&oacute;n de pago</label>
						<input type="text" class="form-control"
							id="folioVerificacionPagoInput" name="folioVerificacionPagoInput"
							placeholder="000000">
					</div>


					<div class="form-group hide" id="numeroFolioEncontrado">
						<div class="alert alert-warning alert-dismissable">
							<button type="button" class="close"
								id="buttonNumeroFolioEncontrado" aria-hidden="true">&times;</button>
							<h4>
								<i class="icon fa fa-warning"></i> Ops !
							</h4>
							<p>El n&uacute;mero de folio ya existe</p>
						</div>
					</div>

				</div>
				<div class="modal-footer">

					<button type="submit" class="btn btn-outline">
						<span class="fa fa-check"></span>
					</button>

				</div>

			</form>
		</div>
	</div>

</div>
<!-- Termina Modal verificacion PEC Autopago -->

