<section class="content-header">
	<h1>
		Angkor <small>Sistema de Atenci&oacute;n al cliente</small>
	</h1>
	<ol class="breadcrumb">
		<li class="active"><i></i>Home</li>
	</ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<!--<h3 class="box-title">Informaci&oacute;n de Mis Proyectos</h3>-->
				</div>
				<!-- /.box-header -->
				<div class="box-body">
					<!-- <table id="example1" class="table table-bordered table-hover">-->

				</div>
				<!-- /.box-body -->
			</div>
			<!-- /.box -->
		</div>
		<!-- /.col -->
	</div>
	<!-- /.row -->
</section>